/**
 * HITR - 100 House Cooling Architectural Designs
 * Part 3: Designs 71 to 100
 * Covers: Airflow & Ventilation Tech (71-76), Active & Mechanical (77-83), Low-Cost DIY Hacks (84-90), Advanced & Experimental (91-100)
 */

import { CoolingDesign } from '../types';

export const DESIGNS_PART_3: CoolingDesign[] = [
  // -------------------------------------------------------------
  // CATEGORY 8: AIRFLOW & VENTILATION TECH (71 - 76)
  // -------------------------------------------------------------
  {
    id: 71,
    name: 'Whole-House Ducted Attic Evacuation Fan',
    category: 'Airflow & Ventilation Tech',
    categorySlug: 'airflow-ventilation-tech',
    costLevel: 'Moderate',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Artificial / Mechanical',
    houseZone: 'Ventilation & Airflow',
    climateSuitability: ['All Climates', 'Temperate', 'Hot-Arid', 'Mediterranean'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '4°C – 8°C evening indoor cool-down in 15–30 minutes',
    tempDropCelsiusRange: [3.5, 7],
    estimatedCostRangeUSD: '$500 – $1,800',
    summary: 'A powerful ceiling-mounted fan in the central hallway ceiling that pulls cool evening outdoor air through open bedroom windows and exhausts hot indoor air through the attic.',
    architecturalPrinciple: 'High-volume convective air exchange (3,000–6,000 CFM): Exchanging the entire air volume of the house 20–30 times per hour rapidly flushes out stored daytime heat and cools interior structural mass.',
    constructionNotes: 'Cut ceiling opening in central hallway, frame header box, and mount insulated self-closing motorized dampers. Ensure adequate attic exhaust vents (1 sq ft of net free attic vent area per 750 CFM).',
    pros: ['Cools the entire house to outdoor evening temperature in just 15-20 minutes', 'Uses 90% less electricity than central air conditioning compressors (150-350W vs 3500W)', 'Simultaneously purges superheated attic air out of roof vents'],
    cons: ['Requires opening windows before turning on to prevent backdrafting gas water heaters or fireplaces', 'Cannot cool below outdoor ambient temperature'],
    maintenanceNotes: 'Check fan belt tension (if belt-driven) and lubricate bearings annually.',
    materialsNeeded: ['Whole house fan unit with ECM motor & insulated damper', 'Ceiling intake louver grille', '2-speed / variable wall switch or remote'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Mid-20th century American classic that remains one of the highest ROI energy-saving retrofits.',
    tags: ['Whole House Fan', 'Evening Flush', 'Massive Airflow', 'Energy Saver', 'High ROI']
  },
  {
    id: 72,
    name: 'Reversible DC Ceiling Fans (Aerodynamic Airfoil Blades)',
    category: 'Airflow & Ventilation Tech',
    categorySlug: 'airflow-ventilation-tech',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Ventilation & Airflow',
    climateSuitability: ['All Climates', 'Hot-Humid', 'Tropical', 'Mediterranean'],
    coolingMechanism: 'Sensory / Convective Chill',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '3°C – 5°C perceived physiological wind-chill drop',
    tempDropCelsiusRange: [2.5, 4.5],
    estimatedCostRangeUSD: '$80 – $350 per fan',
    summary: 'Ceiling-mounted fans with aerodynamically contoured blades driven by ultra-quiet, energy-efficient DC motors running counter-clockwise in summer to create a downward cooling breeze.',
    architecturalPrinciple: 'Convective skin heat dissipation: Air movement of 1.0–1.5 m/s thins the thermal boundary layer around the human body and accelerates sweat evaporation, making a 28°C (82°F) room feel like 24°C (75°F).',
    constructionNotes: 'Hang fan blades at least 2.1 to 2.7 meters above finished floor. In summer, set rotation counter-clockwise (downdraft). Select brushless DC motors consuming just 5–30W.',
    pros: ['Allows raising air-conditioning thermostat by 4°F (2.2°C) with zero loss of human thermal comfort, cutting AC bills by 15-20%', 'Extremely cheap to run (under 2 cents per day on DC motors)', 'Whisper-quiet operation and modern aesthetic lighting integration'],
    cons: ['Cools people, not empty rooms (should be turned off when leaving the room)', 'Does not lower actual thermometer dry-bulb air temperature'],
    maintenanceNotes: 'Dust fan blades every few months with a microfiber cloth.',
    materialsNeeded: ['Energy Star DC motor ceiling fan', 'Ceiling junction electrical box rated for fan support (50 lbs)'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Commercialized in the late 19th century and universal worldwide across tropical regions.',
    tags: ['Ceiling Fan', 'Wind Chill', 'DC Motor', 'Sensory Cooling', 'Low Wattage', 'DIY']
  },
  {
    id: 73,
    name: 'High-Volume Low-Speed (HVLS) Architectural Big Fans',
    category: 'Airflow & Ventilation Tech',
    categorySlug: 'airflow-ventilation-tech',
    costLevel: 'Expensive',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Artificial / Mechanical',
    houseZone: 'Ventilation & Airflow',
    climateSuitability: ['All Climates', 'Hot-Humid', 'Tropical'],
    coolingMechanism: 'Sensory / Convective Chill',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '4°C – 6°C perceived wind chill cooling over vast floor areas',
    tempDropCelsiusRange: [3, 5.5],
    estimatedCostRangeUSD: '$1,800 – $5,500',
    summary: 'Large-diameter (2.4 to 4.2 meter) architectural ceiling fans with engineered aircraft airfoil blades rotating slowly to move massive columns of non-turbulent air.',
    architecturalPrinciple: 'Aerodynamic momentum: Large diameter creates a massive cylinder of gentle, laminar air that travels down to the floor, spreading out horizontally in a 360° deep "floor jet" boundary layer across expansive open-plan spaces.',
    constructionNotes: 'Requires minimum ceiling height of 3.2 meters (10.5 ft) and structural ceiling beam anchoring rated for dynamic rotational torque.',
    pros: ['Moves 4x to 6x more air than standard ceiling fans at ultra-low RPM without annoying wind turbulence or paper fluttering', 'Whisper-quiet acoustic sound profile', 'Spectacular focal centerpiece in modern double-height living rooms and vaulted pavilions'],
    cons: ['Requires high architectural ceilings (not suitable for standard 8ft ceilings)', 'Higher initial purchase price than conventional domestic fans'],
    maintenanceNotes: 'Inspect structural mounting bolts and safety cables annually.',
    materialsNeeded: ['Architectural HVLS ceiling fan (8-12 ft diameter)', 'Structural beam clamp kit and downrod', 'Digital wall controller'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Pioneered in agricultural cooling and modernized for high-end open-plan bioclimatic residential architecture.',
    tags: ['HVLS Fan', 'Big Airfoil', 'Double Height Ceilings', 'Laminar Breeze', 'Luxury Modern']
  },
  {
    id: 74,
    name: 'Window-Mounted Smart Reversible Dual Fans',
    category: 'Airflow & Ventilation Tech',
    categorySlug: 'airflow-ventilation-tech',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Temperate', 'Hot-Arid'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '3°C – 6°C rapid room temperature drop in evening',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$35 – $90 per window unit',
    summary: 'A compact plug-in dual fan unit with expandable side accordion panels that fits into open window frames, featuring independently reversible intake/exhaust motors.',
    architecturalPrinciple: 'Forced directional cross-ventilation: One fan draws in cool night air on the windward/shaded side of the house while another fan in an opposing room exhausts hot stale air.',
    constructionNotes: 'No tools required. Place in open double-hung or slider window, pull out side accordion panels to seal air gaps, and plug into standard electrical outlet. Set built-in thermostat.',
    pros: ['Inexpensive 5-minute setup with zero permanent modifications (ideal for renters)', 'Thermostat automation turns fans on automatically when outdoor air cools below room temperature', 'Significantly accelerates natural evening cooling'],
    cons: ['Must be removed or closed when leaving home unattended for security and rain protection', 'Mild fan motor humming noise on highest speed setting'],
    maintenanceNotes: 'Wipe dust off fan grilles and blades seasonally.',
    materialsNeeded: ['Twin-blade electronically reversible window fan unit with digital thermostat'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Popularized in suburban apartment and residential retrofits since the 1960s.',
    tags: ['Window Fan', 'Reversible Fan', 'Renter Friendly', 'Cheap', 'Evening Flush', 'DIY']
  },
  {
    id: 75,
    name: 'Sub-Floor Plenums & Cool Crawlspace Air Scavenging',
    category: 'Airflow & Ventilation Tech',
    categorySlug: 'airflow-ventilation-tech',
    costLevel: 'Moderate',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Subterranean & Foundation',
    climateSuitability: ['Hot-Arid', 'Temperate', 'Mediterranean'],
    coolingMechanism: 'Subterranean Heat Sink',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '3°C – 6°C supply air pre-cooling',
    tempDropCelsiusRange: [3, 5.5],
    estimatedCostRangeUSD: '$800 – $3,000',
    summary: 'Venting systems that draw naturally chilled ground air from sealed, clean sub-floor crawlspaces or gravel basements into the living areas through decorative floor grilles.',
    architecturalPrinciple: 'The ground beneath a shaded house stays 5°C–10°C cooler than hot ambient summer air. Utilizing small low-wattage booster fans pulls this chilled air upward into living zones.',
    constructionNotes: 'Crawlspace MUST be completely encapsulated with thick 20-mil sealed vapor barrier, dry, clean, and tested for radon to guarantee pristine indoor air quality. Install inline HEPA filters.',
    pros: ['Harnesses free natural subterranean cool air without digging external trenches', 'Operates with tiny low-wattage 20W DC inline booster fans', 'Floor grilles deliver cool air right at occupant level where it is needed most'],
    cons: ['Requires strict crawlspace encapsulation and radon/mold mitigation checks', 'Not suitable in damp, flooded, or unsealed dirt crawlspaces'],
    maintenanceNotes: 'Replace inline HEPA air filters every 6 months; inspect crawlspace humidity.',
    materialsNeeded: ['20-mil sealed crawlspace vapor barrier', 'Inline duct booster fan with speed controller', 'MERV 13 / HEPA air filter box', 'Cast-iron floor registers'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Adapted from traditional Japanese raised tatami floor ventilation and Victorian underfloor cooling plenums.',
    tags: ['Subfloor Cooling', 'Crawlspace Air', 'Floor Registers', 'Ground Sourced']
  },
  {
    id: 76,
    name: 'Energy Recovery Ventilators (ERV with Enthalpy Core)',
    category: 'Airflow & Ventilation Tech',
    categorySlug: 'airflow-ventilation-tech',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Artificial / Mechanical',
    houseZone: 'Mechanical & Active',
    climateSuitability: ['All Climates', 'Hot-Humid', 'Extreme Climates'],
    coolingMechanism: 'Mechanical Vapor-Compression',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: 'Pre-conditions 70-80% of ventilation thermal/humidity load',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$2,200 – $6,500',
    summary: 'A balanced mechanical ventilation unit that continuously exchanges stale indoor air for fresh outdoor air, transferring both sensible heat and moisture humidity between air streams.',
    architecturalPrinciple: 'Enthalpy exchange membrane: Hot humid incoming fresh air transfers its thermal heat and moisture vapor to the cool exhaust air stream before entering the house, delivering cool, dry, filtered fresh air.',
    constructionNotes: 'Connect dedicated supply ducts to bedrooms/living areas and exhaust ducts to kitchens/bathrooms. Balance airflow CFM precisely using a digital manometer.',
    pros: ['Supplies continuous 100% fresh, filtered outdoor air without losing expensive air-conditioned indoor cooling', 'Crucial for airtight, high-performance modern Passivhaus homes', 'Removes indoor VOCs, CO₂, cooking odors, and pollen with MERV 13 filtration'],
    cons: ['Requires dedicated ductwork routing and condensate drainage line', 'Filters must be cleaned or replaced regularly'],
    maintenanceNotes: 'Clean or replace core filters every 3–6 months; inspect enthalpy core annually.',
    materialsNeeded: ['High-efficiency ERV unit with EC motors (e.g. Zehnder, Broan)', 'Insulated flexible/rigid ventilation ducting', 'Exterior intake/exhaust wall hoods'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Pioneered in Canadian and German advanced building science and Passivhaus standards.',
    tags: ['ERV', 'Energy Recovery', 'Enthalpy Core', 'Fresh Air', 'Passivhaus', 'Humidity Control']
  },

  // -------------------------------------------------------------
  // CATEGORY 9: ACTIVE & MECHANICAL SOLUTIONS (77 - 83)
  // -------------------------------------------------------------
  {
    id: 77,
    name: 'Ground-Source Geothermal Heat Pump (Closed-Loop Ground Loop)',
    category: 'Active & Mechanical Solutions',
    categorySlug: 'active-mechanical-solutions',
    costLevel: 'Very Expensive',
    effortLevel: 'High',
    difficulty: 'Extremely Difficult',
    nature: 'Artificial / Mechanical',
    houseZone: 'Subterranean & Foundation',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Extreme Climates', 'Temperate'],
    coolingMechanism: 'Geothermal Exchange',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: 'Full whole-house cooling at 400-500% thermal efficiency (COP > 4.5)',
    tempDropCelsiusRange: [5, 12],
    estimatedCostRangeUSD: '$12,000 – $35,000',
    summary: 'Pumping water/antifreeze through deep vertical or horizontal underground polyethylene pipes to reject household heat into the stable 12°C–16°C earth.',
    architecturalPrinciple: 'Thermodynamic ground heat sink: Air-source AC units struggle to reject heat into 40°C outdoor air. Geothermal rejects heat into 14°C ground, cutting electrical energy consumption by up to 50–70%.',
    constructionNotes: 'Drill vertical boreholes (60–100 meters deep) or excavate horizontal trenches. Install continuous thermally fused HDPE pipes backfilled with bentonite thermal grout.',
    pros: ['The highest efficiency, lowest-operating-cost heating and cooling system available on earth', 'Underground ground loops last 50 to 100+ years with zero maintenance', 'No noisy outdoor air condenser fans visible on the patio'],
    cons: ['High initial excavation and drilling installation expense', 'Requires yard area or borehole drilling rig site access'],
    maintenanceNotes: 'Standard indoor air filter changes and annual glycol loop pressure check.',
    materialsNeeded: ['Water-to-air geothermal heat pump unit', 'High-density polyethylene (HDPE) ground loop pipe', 'Thermal conductive grout'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Commercialized in the 1970s and refined as the gold standard of zero-carbon building mechanical systems.',
    tags: ['Geothermal', 'Ground Source', 'Extreme Efficiency', 'Zero Carbon', 'Ground Loop']
  },
  {
    id: 78,
    name: 'Inverter Ductless Multi-Split Air Conditioning (SEER2 25+)',
    category: 'Active & Mechanical Solutions',
    categorySlug: 'active-mechanical-solutions',
    costLevel: 'Moderate',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Artificial / Mechanical',
    houseZone: 'Mechanical & Active',
    climateSuitability: ['All Climates', 'Hot-Humid', 'Hot-Arid', 'Tropical'],
    coolingMechanism: 'Mechanical Vapor-Compression',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: 'Precise room temperature control (down to 18°C / 64°F)',
    tempDropCelsiusRange: [5, 15],
    estimatedCostRangeUSD: '$1,200 – $4,500 per zone (DIY pre-charged line kits available)',
    summary: 'Wall-mounted whisper-quiet indoor air handlers connected to a variable-speed outdoor compressor via small refrigerant lines, providing independent room-by-room zoned cooling.',
    architecturalPrinciple: 'Variable-capacity inverter modulation: Instead of cycling on/off like old central AC units, modern DC inverters throttle down to 10% speed, maintaining precise temperature with ultra-low electricity draw.',
    constructionNotes: 'Requires a single 75 mm hole through the exterior wall for refrigerant lines, power cable, and condensate drain. DIY quick-connect pre-charged line-sets allow straightforward homeowner installation.',
    pros: ['Eliminates energy-wasting ductwork losses (which waste 20-30% of cooling in standard attics)', 'Zoned control: only cool the specific room you are currently occupying', 'Whisper quiet indoor sound levels (< 19 dBA, quieter than a whisper)'],
    cons: ['Visible wall-mounted indoor air handler units', 'Requires dedicated electrical circuit from main breaker panel'],
    maintenanceNotes: 'Wash reusable nylon dust filters every month; rinse outdoor condenser coil yearly.',
    materialsNeeded: ['Inverter mini-split heat pump system (SEER 20-30+)', 'Pre-charged line set & wall mounting bracket', 'Decorative line-set cover kit'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Invented in Japan by Toshiba/Daikin in 1981, now the dominant cooling technology across Asia and Europe.',
    tags: ['Mini Split', 'Inverter AC', 'Zoned Cooling', 'High SEER', 'DIY Friendly']
  },
  {
    id: 79,
    name: 'Direct DC Solar-Powered Air Conditioning (PV-Direct)',
    category: 'Active & Mechanical Solutions',
    categorySlug: 'active-mechanical-solutions',
    costLevel: 'Expensive',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Hybrid',
    houseZone: 'Mechanical & Active',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Tropical', 'Mediterranean'],
    coolingMechanism: 'Mechanical Vapor-Compression',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: 'Full room cooling at 100% zero grid electric cost during peak sun',
    tempDropCelsiusRange: [5, 14],
    estimatedCostRangeUSD: '$2,200 – $5,500',
    summary: 'A mini-split heat pump that accepts raw DC electricity directly from 3 to 6 rooftop solar panels without needing an expensive inverter or batteries.',
    architecturalPrinciple: 'Direct solar-cooling coincidence: Peak building cooling demand aligns 100% with maximum solar panel electricity production during scorching sunny afternoons.',
    constructionNotes: 'Connect 3–6 solar PV panels (e.g. 400W each) directly to the outdoor compressor DC terminal lugs via MC4 solar cables. Also connects to standard AC grid power for seamless evening operation.',
    pros: ['Runs 100% free on direct daytime solar power when cooling demand is highest', 'Requires no expensive battery bank or grid-tie interconnection permit', 'Significantly offsets peak summer electric utility tier rates'],
    cons: ['Higher upfront equipment cost than basic AC units', 'Requires unshaded roof space for solar panels'],
    maintenanceNotes: 'Wipe solar panels clean twice a year.',
    materialsNeeded: ['Hybrid DC solar mini-split AC unit', '3 to 6 high-wattage solar panels (350W–450W)', 'Solar roof racking & MC4 cables'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Pioneered in off-grid solar technology and modernized for grid-tied residential energy resilience.',
    tags: ['Solar AC', 'PV Direct', 'Zero Grid Bill', 'Peak Sun Coincidence', 'Hybrid Solar']
  },
  {
    id: 80,
    name: 'Hydronic Radiant Cooling Floors & Ceilings',
    category: 'Active & Mechanical Solutions',
    categorySlug: 'active-mechanical-solutions',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Artificial / Mechanical',
    houseZone: 'Walls & Envelope',
    climateSuitability: ['Hot-Arid', 'Mediterranean', 'Temperate'],
    coolingMechanism: 'Thermal Mass / Lag',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '3°C – 6°C mean radiant temperature (MRT) reduction',
    tempDropCelsiusRange: [3, 5.5],
    estimatedCostRangeUSD: '$5,000 – $16,000',
    summary: 'Circulating chilled water (16°C–19°C) through embedded PEX tubing inside polished concrete floor slabs or drywall ceiling panels.',
    architecturalPrinciple: 'Mean Radiant Temperature (MRT) control: 50% of human body heat loss occurs via radiant exchange with surrounding surfaces. Chilling the floor/ceiling absorbs body radiation directly without noisy drafts.',
    constructionNotes: 'CRITICAL: Must integrate smart dew-point sensors and dedicated dehumidification to keep chilled water supply temperature strictly 1.5°C above indoor dew-point, preventing floor condensation sweating.',
    pros: ['Sensational, draft-free, silent thermal comfort with no blowing air or dust circulation', 'Operates with warm chilled water (18°C vs 7°C for forced air), boosting chiller COP efficiency', 'Can share the exact same PEX tubing for winter radiant floor heating'],
    cons: ['Strict condensation risk management required (requires dedicated dehumidifiers in humid zones)', 'Slow thermal response time (best kept running at steady temperature)'],
    maintenanceNotes: 'Annual manifold valve inspection and water pressure check.',
    materialsNeeded: ['Embedded PEX-A hydronic barrier tubing', 'Chilled water heat pump / chiller', 'Smart dew-point sensor mixing manifold'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Used in Roman hypocausts (in reverse) and modernized in premier European bioclimatic architecture.',
    tags: ['Radiant Cooling', 'Hydronic Floor', 'Dew Point Sensor', 'Draft Free Comfort']
  },
  {
    id: 81,
    name: 'Passive & Active Chilled Beams',
    category: 'Active & Mechanical Solutions',
    categorySlug: 'active-mechanical-solutions',
    costLevel: 'Very Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Artificial / Mechanical',
    houseZone: 'Mechanical & Active',
    climateSuitability: ['Temperate', 'Hot-Arid', 'Commercial / Luxury'],
    coolingMechanism: 'Sensory / Convective Chill',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '4°C – 8°C convective room cooling',
    tempDropCelsiusRange: [3.5, 7],
    estimatedCostRangeUSD: '$3,500 – $12,000',
    summary: 'Ceiling-suspended architectural finned copper coils circulating chilled water that cool rising warm ceiling air, creating a natural descending convective cool air cascade.',
    architecturalPrinciple: 'Convective gravity cascade: Warm air rises to the ceiling, cools against chilled water beam coils, becomes denser, and gently sinks into the occupied living zone without fans.',
    constructionNotes: 'Requires a dedicated outdoor air system (DOAS) to supply dry dehumidified fresh ventilation air. Suspended from structural ceiling beams with exposed architectural casing.',
    pros: ['100% silent convective cooling with zero moving fan parts in the room', 'Low maintenance (no fan motors or local electrical connections)', 'High aesthetic architectural elegance in modern industrial/contemporary interiors'],
    cons: ['High capital cost for hydronic piping, chillers, and DOAS dehumidification', 'Risk of dripping condensation if primary fresh air is not pre-dehumidified'],
    maintenanceNotes: 'Vacuum finned coil lint annually.',
    materialsNeeded: ['Chilled beam cassettes (active or passive)', 'Insulated copper/PEX hydronic supply lines', 'Central water chiller with condensation sensor'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Developed in Scandinavian commercial architecture and adapted into luxury sustainable residences.',
    tags: ['Chilled Beam', 'Silent Cooling', 'Hydronic Cascade', 'High Tech']
  },
  {
    id: 82,
    name: 'Thermal Ice-Storage Air Conditioning (Off-Peak Phase Shift)',
    category: 'Active & Mechanical Solutions',
    categorySlug: 'active-mechanical-solutions',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Artificial / Mechanical',
    houseZone: 'Mechanical & Active',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Temperate'],
    coolingMechanism: 'Phase Change',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: 'Full house daytime cooling using zero daytime peak electric power',
    tempDropCelsiusRange: [4, 10],
    estimatedCostRangeUSD: '$4,000 – $14,000',
    summary: 'A system that runs a high-efficiency chiller overnight to freeze a thermal storage water/ice tank when electricity is cheap and cool, then circulates chilled ice water during peak daytime heat.',
    architecturalPrinciple: 'Latent heat thermal storage: Freezing 1 kg of ice stores 334 kJ of latent cold energy. Discharging this stored cold during expensive peak-rate afternoon hours slashes electric bills and grid strain.',
    constructionNotes: 'Install insulated thermal storage ice tank in basement, garage, or outdoor equipment pad. Connect via heat exchanger to existing HVAC air handler coil.',
    pros: ['Capitalizes on cheap super-off-peak nighttime electric utility rates', 'Takes massive strain off municipal electrical grids during statewide heat emergencies', 'Provides backup cooling during daytime rolling power brownouts'],
    cons: ['Requires physical space footprint for the thermal ice tank', 'Higher initial investment cost than standard conventional AC units'],
    maintenanceNotes: 'Annual glycol concentration and pump inspection.',
    materialsNeeded: ['Insulated thermal ice-storage tank with internal coils', 'High-efficiency condensing chiller', 'Automated phase-shift control board'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Derived from 19th-century commercial icehouse engineering and modernized for smart grid peak-shaving.',
    tags: ['Ice Storage', 'Thermal Battery', 'Off Peak', 'Peak Shaving', 'Grid Resilience']
  },
  {
    id: 83,
    name: 'Solid-Desiccant Solar Regenerative Dehumidification Cooling',
    category: 'Active & Mechanical Solutions',
    categorySlug: 'active-mechanical-solutions',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Hybrid',
    houseZone: 'Mechanical & Active',
    climateSuitability: ['Hot-Humid', 'Tropical', 'Coastal'],
    coolingMechanism: 'Mechanical Vapor-Compression',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: 'Dramatically lowers humidity (down to 40% RH), making 29°C feel like 23°C',
    tempDropCelsiusRange: [3, 6],
    estimatedCostRangeUSD: '$3,800 – $11,000',
    summary: 'A rotating honeycomb wheel coated with silica gel that adsorbs moisture from incoming humid air, regenerated and dried using free heat from solar thermal roof collectors.',
    architecturalPrinciple: 'Enthalpy decoupling: Separates latent cooling (moisture removal) from sensible cooling (temperature drop). Dry air allows human sweat to evaporate effortlessly, achieving comfort at higher temperatures.',
    constructionNotes: 'Integrate desiccant wheel rotor with solar thermal flat-plate roof collectors (generating 60°C–80°C hot water/air) to continuously bake and regenerate the moisture-laden silica gel.',
    pros: ['Transforms sticky, oppressive tropical humidity into crisp, mountain-fresh indoor air', 'Operates desiccant regeneration using 100% free rooftop solar thermal heat', 'Prevents mold, mildew, and dust mite proliferation completely'],
    cons: ['Complex mechanical ducting and solar thermal loop integration', 'Higher initial system complexity'],
    maintenanceNotes: 'Inspect desiccant rotor drive belt and solar thermal fluid annually.',
    materialsNeeded: ['Desiccant rotor wheel cassette (silica gel / zeolite)', 'Solar thermal collector panels', 'Supply/exhaust air blowers'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Pioneered in industrial climate control and advanced solar air-conditioning engineering.',
    tags: ['Desiccant Cooling', 'Solar Thermal Regeneration', 'Humidity Control', 'Tropical Comfort']
  },

  // -------------------------------------------------------------
  // CATEGORY 10: SMALL EFFORT / LOW-COST "HACKS" (84 - 90)
  // -------------------------------------------------------------
  {
    id: 84,
    name: 'DIY Emergency Ice-Bucket Swamp Cooler',
    category: 'Small Effort / Low-Cost "Hacks"',
    categorySlug: 'low-cost-diy-hacks',
    costLevel: 'Free',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Low-Cost DIY Hacks',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Temperate'],
    coolingMechanism: 'Sensory / Convective Chill',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '5°C – 10°C cold spot air stream drop',
    tempDropCelsiusRange: [4, 9],
    estimatedCostRangeUSD: '$10 – $30 (or free with scrap items)',
    summary: 'A 5-gallon plastic bucket filled with frozen water jugs or ice, with 3 PVC outlet nozzles and a small 12V desk fan mounted into the lid blowing air over the ice.',
    architecturalPrinciple: 'Forced convective sensible heat transfer: The small fan forces warm room air across the frozen ice bottles (0°C surface), discharging a steady stream of 10°C (50°F) chilled air directly at the occupant.',
    constructionNotes: 'Drill 3 holes (50 mm) in the side of a 5-gallon bucket and insert short PVC elbows angled upward. Cut a hole in the lid, screw in a 12V PC fan or small desk fan, and plug in a USB power bank.',
    pros: ['Immediate lifesaver during heatwaves and power outages (can run for 24+ hours on a small USB battery)', 'Costs almost nothing to build from scrap parts in 20 minutes', 'Uses frozen water bottles (reusable, no mess or puddle cleanup)'],
    cons: ['Spot cooling only (cools an individual chair or bed, not an entire house)', 'Ice bottles must be refrozen every 4-6 hours'],
    maintenanceNotes: 'Refreeze water bottles between uses.',
    materialsNeeded: ['5-gallon plastic bucket with lid', 'Small 5V/12V USB fan', '3x PVC pipe elbows (2")', 'Frozen 2-liter water bottles'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Viral emergency maker hack used during heatwaves and off-grid camping.',
    tags: ['Bucket Cooler', 'Emergency Hack', 'USB Fan', 'Off Grid', 'Zero Cost', 'DIY']
  },
  {
    id: 85,
    name: 'Thermal Blackout Curtains with Silver Reflective Backing',
    category: 'Small Effort / Low-Cost "Hacks"',
    categorySlug: 'low-cost-diy-hacks',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '3°C – 6°C room temperature drop on sunny facades',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$20 – $70 per window',
    summary: 'Triple-weave dense blackout drapery with a white or silver metallized exterior-facing thermal backing that blocks 100% of light and reflects incoming heat.',
    architecturalPrinciple: 'Traps a stagnant thermal boundary layer of air between the fabric and window glass while high-reflectance backing bounces solar radiation back out through the pane.',
    constructionNotes: 'Hang curtains high and wide (extending 15 cm past window frames on all sides) and let them touch the floor or windowsill to seal convective air edge loops.',
    pros: ['Inexpensive, attractive, and installs in 15 minutes on standard curtain rods', 'Blocks 99% of harsh sun glare and outdoor street noise', 'Keeps bedrooms dark and cool for deep, restorative sleep'],
    cons: ['Must be closed during the day, which eliminates outdoor views and natural daylight', 'Less efficient than exterior shutters (some heat is still trapped at the glass)'],
    maintenanceNotes: 'Machine wash on delicate cycle annually.',
    materialsNeeded: ['Thermal insulated blackout curtain panels with silver/white backing', 'Curtain rod & mounting brackets'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Standard low-cost energy efficiency upgrade used globally.',
    tags: ['Blackout Curtains', 'Thermal Drapes', 'Cheap', 'DIY', 'Sleep Comfort']
  },
  {
    id: 86,
    name: '100% LED Relamping (Eliminating Internal Incandescent Heat Loads)',
    category: 'Small Effort / Low-Cost "Hacks"',
    categorySlug: 'low-cost-diy-hacks',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Low-Cost DIY Hacks',
    climateSuitability: ['All Climates'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '1°C – 2.5°C reduction in unnecessary internal room heat load',
    tempDropCelsiusRange: [1, 2.5],
    estimatedCostRangeUSD: '$20 – $60 (Whole house bulb pack)',
    summary: 'Replacing all legacy incandescent and halogen light bulbs with high-efficiency LED bulbs throughout the home.',
    architecturalPrinciple: 'Internal heat gain reduction: Incandescent bulbs convert 90% of electrical energy directly into waste radiant heat (a 100W bulb is literally a 90W electric space heater). LEDs produce 85% less heat for equal lumens.',
    constructionNotes: 'Unscrew old hot incandescent or halogen bulbs and screw in warm-white (2700K–3000K) or daylight (4000K) LED bulbs.',
    pros: ['Immediately eliminates internal parasitic thermal space heating', 'Cuts lighting electric bill by 80–90%', 'LED bulbs last 15,000–25,000 hours (15+ years of daily use)'],
    cons: ['Ensure compatibility with older wall dimmer switches (use dimmable LEDs)', 'Old halogen fixtures may require LED driver replacement'],
    maintenanceNotes: 'Zero maintenance.',
    materialsNeeded: ['Multi-pack Energy Star LED light bulbs (E26 / GU10 / A19)'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Global standard lighting transition following modern semiconductor breakthroughs.',
    tags: ['LED Lighting', 'Internal Heat Elimination', 'Super Cheap', '5 Min DIY', 'Instant ROI']
  },
  {
    id: 87,
    name: 'Outdoor Summer Kitchen & Induction Cooktops',
    category: 'Small Effort / Low-Cost "Hacks"',
    categorySlug: 'low-cost-diy-hacks',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Low-Cost DIY Hacks',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '2°C – 4°C elimination of kitchen indoor heat spikes',
    tempDropCelsiusRange: [1.5, 3.5],
    estimatedCostRangeUSD: '$50 – $350 (Portable induction / grill)',
    summary: 'Cooking meals outdoors on a covered patio grill, smoker, or portable magnetic induction cooktop during summer to keep oven and stove heat out of the house.',
    architecturalPrinciple: 'Source heat load isolation: Gas ovens and stovetops generate 5,000–20,000 BTUs/hour of sensible heat and moisture humidity directly inside the conditioned house envelope.',
    constructionNotes: 'Set up a shaded outdoor food prep station on the veranda or use a portable plug-in induction burner on the patio table.',
    pros: ['Eliminates the single largest source of internal daytime household heat and humidity generation', 'Fun, social outdoor cooking experience with family and guests', 'Induction cookers transfer 90% of energy directly to the pan with zero open flame waste heat'],
    cons: ['Weather dependent (requires covered porch during heavy rain)', 'Slightly less convenient than walking to the indoor kitchen'],
    maintenanceNotes: 'Wipe cooktop clean after use; cover outdoor grill.',
    materialsNeeded: ['Portable single/double burner induction cooktop or outdoor BBQ grill', 'Outdoor heavy-duty extension cord'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Standard architectural feature of 18th/19th-century American Southern plantations, Mediterranean summer kitchens, and Russian letnyaya kukhnya.',
    tags: ['Summer Kitchen', 'Outdoor Cooking', 'Induction', 'No Internal Heat', 'DIY']
  },
  {
    id: 88,
    name: 'Damp Linen Nocturnal Siphoning (Ancient Egyptian Sleep Method)',
    category: 'Small Effort / Low-Cost "Hacks"',
    categorySlug: 'low-cost-diy-hacks',
    costLevel: 'Free',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Low-Cost DIY Hacks',
    climateSuitability: ['Hot-Arid', 'Mediterranean', 'Dry Summer'],
    coolingMechanism: 'Evaporative Cooling',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '4°C – 8°C personal microclimate skin cooling',
    tempDropCelsiusRange: [3.5, 7.5],
    estimatedCostRangeUSD: '$0 (100% Free)',
    summary: 'Dampening a 100% breathable cotton or linen bedsheet with cool water, wringing it out until barely damp, and using it as a top sleeping sheet under a ceiling fan.',
    architecturalPrinciple: 'Conductive and evaporative personal microclimate cooling: As the ceiling fan breeze washes over the damp sheet, continuous evaporation absorbs latent heat directly from the sleeper’s skin.',
    constructionNotes: 'Wash a light cotton sheet in cold water and run through the washing machine spin cycle (or wring out firmly by hand) so it is cool and damp, not soaking wet.',
    pros: ['Provides instant, deep cooling relief on the hottest tropical/desert summer nights without air conditioning', '100% free and requires zero equipment or tools', 'Natural and non-toxic method for instant restful sleep during power blackouts'],
    cons: ['Only works well in dry/moderate humidity (in extreme humid climates sheet stays wet without evaporating)', 'Sheet dries out after 4 to 6 hours'],
    maintenanceNotes: 'Wash sheet normally.',
    materialsNeeded: ['100% lightweight cotton or pure linen flat bed sheet', 'Water'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Recorded ancient Egyptian nocturnal lifestyle along the Nile River valley.',
    tags: ['Egyptian Sleep Method', 'Damp Sheet', 'Zero Cost', 'Emergency Sleep', 'Free Cooling']
  },
  {
    id: 89,
    name: 'Painting Outdoor Patios & Window Surrounds High-Albedo White',
    category: 'Small Effort / Low-Cost "Hacks"',
    categorySlug: 'low-cost-diy-hacks',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Landscape & Site',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Mediterranean'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '10°C – 20°C patio surface temperature drop',
    tempDropCelsiusRange: [2, 4.5],
    estimatedCostRangeUSD: '$40 – $150',
    summary: 'Painting dark outdoor concrete steps, patio slabs, window sills, and outdoor furniture with bright white reflective masonry or porch paint.',
    architecturalPrinciple: 'Albedo modification of window boundary microclimates: Dark patio slabs directly outside south/west windows heat to 55°C+, creating a thermal updraft that conducts heat into the window.',
    constructionNotes: 'Clean concrete patio with degreaser, apply concrete bonding primer, and roll 2 coats of non-skid white acrylic porch & floor paint.',
    pros: ['Drastically lowers radiant thermal heat reflecting into nearby living room windows', 'Patio stays cool enough to walk on with bare feet on sunny afternoons', 'Fast, rewarding weekend DIY home improvement'],
    cons: ['White patios require occasional sweeping or pressure washing to keep clean', 'Bright white can cause minor glare if unshaded (use off-white/light sandstone tints)'],
    maintenanceNotes: 'Hose off dirt once a month.',
    materialsNeeded: ['White exterior concrete/porch paint (with non-skid additive)', 'Heavy nap roller & tray'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Standard tradition across Greek islands (Mykonos, Santorini) and Andalusian whitewashed villages.',
    tags: ['White Patio', 'Albedo Paint', 'Cool Hardscape', 'Cheap', 'DIY']
  },
  {
    id: 90,
    name: 'Sealing Fireplace Dampers & Chimney Draft Balloons',
    category: 'Small Effort / Low-Cost "Hacks"',
    categorySlug: 'low-cost-diy-hacks',
    costLevel: 'Free',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Low-Cost DIY Hacks',
    climateSuitability: ['All Climates', 'Temperate', 'Hot-Arid'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '1.5°C – 3°C air conditioning retention / stops reverse draft',
    tempDropCelsiusRange: [1, 2.5],
    estimatedCostRangeUSD: '$0 (Manual close) / $25 – $50 (Inflatable chimney balloon)',
    summary: 'Closing the mechanical iron fireplace damper and inserting an inflatable reusable chimney plug balloon during hot summer months.',
    architecturalPrinciple: 'Eliminates open flue thermal air leaks: An open chimney acts as a massive thermal bypass, constantly sucking expensive conditioned indoor air up the flue or allowing superheated roof chimney air to pour down.',
    constructionNotes: 'Reach inside fireplace, push metal damper lever to closed locked position. For complete airtight seal, insert inflatable chimney draft plug and blow up with hand pump.',
    pros: ['Takes 60 seconds and costs $0 if using built-in fireplace damper lever', 'Stops hot chimney odor and outdoor soot smells from entering the living room', 'Cuts summer cooling and winter heating energy loss by up to 10%'],
    cons: ['Must remember to remove chimney balloon before lighting fires in autumn/winter', 'Dirty hands when accessing older sooty dampers (wear work gloves)'],
    maintenanceNotes: 'Check inflation of chimney plug seasonally.',
    materialsNeeded: ['Inflatable reusable chimney draft stopper balloon (or built-in fireplace damper lever)'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Essential home weatherization rule documented in modern energy audit guidelines.',
    tags: ['Chimney Damper', 'Air Sealing', 'Zero Cost', 'Energy Audit', 'Draft Stopper']
  },

  // -------------------------------------------------------------
  // CATEGORY 11: ADVANCED & EXPERIMENTAL DESIGNS (91 - 100)
  // -------------------------------------------------------------
  {
    id: 91,
    name: '3D-Printed Porous Ceramic Evaporative "Cool Bricks"',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Hybrid',
    houseZone: 'Walls & Envelope',
    climateSuitability: ['Hot-Arid', 'Desert', 'Mediterranean'],
    coolingMechanism: 'Evaporative Cooling',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '5°C – 10°C wall surface and incoming air cooling',
    tempDropCelsiusRange: [4.5, 9],
    estimatedCostRangeUSD: '$4,000 – $15,000',
    summary: '3D-printed modular porous ceramic interlocking bricks designed with complex internal geometric lattices that hold water and evaporate it as breezes pass through.',
    architecturalPrinciple: 'Biomimetic 3D capillary evaporation: Water filled in the brick’s internal porous reservoir wicks through micropores. As hot dry wind passes through the undulating aerodynamic cavity, latent heat vaporization chills the air.',
    constructionNotes: 'Stack interlocking mortarless bricks with internal drip-irrigation feed line. Integrates modular 3D printed terracotta geometry inspired by Muscadel porous pottery.',
    pros: ['Zero-electricity evaporative cooling masonry wall system', 'Sculptural, undulating parametric shadow-relief facade aesthetics', 'Pioneers cutting-edge additive ceramic architecture for climate resilience'],
    cons: ['High manufacturing cost for custom 3D ceramic printing', 'Requires clean water supply to prevent mineral pore clogging in hard-water zones'],
    maintenanceNotes: 'Flush water supply lines biannually.',
    materialsNeeded: ['3D printed porous ceramic / terracotta brick modules', 'Integrated low-pressure drip irrigation manifold'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Engineered by Emerging Objects (Rael San Fratello) combining ancient Muscadel pottery with 3D additive manufacturing.',
    tags: ['Cool Brick', '3D Printed', 'Ceramic Lattice', 'Biomimetic', 'Additive Architecture']
  },
  {
    id: 92,
    name: 'Subterranean Earth Tubes (Ground-Coupled Air Heat Exchangers)',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Subterranean & Foundation',
    climateSuitability: ['Hot-Arid', 'Temperate', 'Extreme Climates'],
    coolingMechanism: 'Subterranean Heat Sink',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '6°C – 14°C incoming fresh air cooling',
    tempDropCelsiusRange: [5, 12],
    estimatedCostRangeUSD: '$3,500 – $11,000',
    summary: 'Burying 30 to 50 meters of smooth-walled antimicrobial polyethylene or polypropylene pipes 2 to 3 meters underground to pre-cool incoming ventilation air via ground thermal exchange.',
    architecturalPrinciple: 'Earth thermal damping: At 2–3 meters underground, soil temperature stays constant at 12°C–16°C year-round. Drawing 38°C outdoor summer air through the underground pipe cools it down to 20°C before entering the house.',
    constructionNotes: 'Slope pipes at 1.5–2% toward a central drainage sump with a condensate trap to drain condensed moisture. Use smooth antimicrobial food-grade PE/PP pipes (avoid corrugated pipes that trap moisture/mold).',
    pros: ['Supplies 100% naturally chilled fresh outdoor air with zero refrigerant or compressors', 'Provides passive winter pre-heating in cold seasons', 'Virtually zero operational cost (powered by a tiny 30W duct fan or solar chimney)'],
    cons: ['Requires extensive yard excavation and trenching (2-3 meters deep)', 'Condensate drainage and radon/airtightness detailing must be rigorously engineered'],
    maintenanceNotes: 'Check condensate sump pump and replace air intake MERV filter biannually.',
    materialsNeeded: ['Antimicrobial rigid underground air pipe (200mm diameter, e.g. Rehau Awadukt)', 'Intake snorkel tower with stainless insect/MERV filter', 'Condensate drainage trap & sump'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Documented in 19th-century agricultural cooling and standardized in German Passivhaus "Erdwärmetauscher" design.',
    tags: ['Earth Tubes', 'Ground Air Exchange', 'Passive Geothermal', 'Zero Refrigerant']
  },
  {
    id: 93,
    name: 'Bio-Based Phase-Change Micro-Encapsulated Drywall (Bio-PCM)',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Expensive',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Walls & Envelope',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Temperate', 'Mediterranean'],
    coolingMechanism: 'Phase Change',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '3°C – 5°C room peak temperature shaving',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$1,500 – $4,500 per room',
    summary: 'Interior wall and ceiling drywall infused with microscopic organic fatty-acid capsules that absorb room heat and melt invisibly at 22°C (72°F).',
    architecturalPrinciple: 'Latent heat thermal damping: As room temperature rises past 22°C, the bio-PCM absorbs 100+ kJ/kg of heat without getting any warmer, capping room temperature and reducing AC runtime by 30%.',
    constructionNotes: 'Hang and finish identically to conventional drywall sheets. Pair with automatic overnight window opening or whole house fan to re-solidify the PCM for the next day.',
    pros: ['Adds massive thermal inertia to lightweight timber-frame walls without adding structural dead weight', 'Non-toxic, bio-based renewable fatty acid formulation (safe and non-hazardous)', 'Straightforward installation during standard room renovation'],
    cons: ['Higher cost than standard gypsum drywall', 'Requires cool overnight indoor temperatures (below 20°C) to discharge latent heat'],
    maintenanceNotes: 'Zero maintenance.',
    materialsNeeded: ['Bio-PCM drywall boards / ceiling panels', 'Drywall fasteners & joint compound'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Cutting-edge materials science commercialized by leading sustainable building manufacturers.',
    tags: ['Bio PCM', 'Latent Heat', 'Smart Gypsum', 'Thermal Capacitor']
  },
  {
    id: 94,
    name: 'Automated Solar-Tracking Heliotropic Exterior Louvers',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Very Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Hybrid',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Mediterranean'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '5°C – 9°C solar heat gain reduction',
    tempDropCelsiusRange: [4, 8],
    estimatedCostRangeUSD: '$3,500 – $14,000',
    summary: 'Motorized exterior aluminum or timber louver blades controlled by solar tracking algorithms that rotate continuously to block 100% of direct sun while preserving daylight.',
    architecturalPrinciple: 'Dynamic solar geometry intercept: As the sun’s azimuth and elevation change minute-by-minute, the motorized louvers rotate to remain perfectly perpendicular to solar rays, preventing 95%+ of direct thermal radiation.',
    constructionNotes: 'Mount exterior structural aluminum support mullions. Wire 24V DC stepper actuators to an astronomical clock or rooftop solar tracker controller.',
    pros: ['The ultimate automated solar protection with zero manual intervention', 'Maintains maximum possible diffuse outdoor views and daylight at all times of the day', 'Ultra-luxurious dynamic kinetic architectural facade appearance'],
    cons: ['High capital investment and mechanical actuator maintenance over time', 'Requires wind sensor to automatically retract or flatten louvers in severe gale windstorms'],
    maintenanceNotes: 'Inspect motorized actuators, pivot bearings, and wind safety sensor biannually.',
    materialsNeeded: ['Motorized extruded aluminum louvers with bearings', '24V DC linear stepper actuators', 'Astronomical solar controller with anemometer'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Inspired by heliotropic plants (sunflowers) and pioneered in cutting-edge kinetic bioclimatic architecture (e.g. Institut du Monde Arabe by Jean Nouvel).',
    tags: ['Solar Tracking', 'Kinetic Louvers', 'Automated Shading', 'Bioclimatic Facade']
  },
  {
    id: 95,
    name: 'Thermally Activated Hollow-Core Concrete Slabs (TermoDeck)',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Hybrid',
    houseZone: 'Orientation & Layout',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Temperate', 'Mediterranean'],
    coolingMechanism: 'Thermal Mass / Lag',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '4°C – 7°C whole-building thermal stabilization',
    tempDropCelsiusRange: [3.5, 6.5],
    estimatedCostRangeUSD: '$5,000 – $18,000',
    summary: 'Precast hollow-core concrete floor slabs connected into a continuous labyrinth ventilation duct system through which supply air circulates to cool the concrete mass.',
    architecturalPrinciple: 'Deep thermal mass activation: Circulating cool nighttime air through the internal tubular voids of precast concrete floor slabs charges the entire structural skeleton with thermal cold energy, keeping rooms cool all day.',
    constructionNotes: 'Connect hollow core slab cores with airtight crossover manifolds. Leave concrete slab undersides exposed as finished interior ceilings without acoustic drop tiles.',
    pros: ['Eliminates the need for overhead suspended ceiling ductwork', 'Cuts HVAC chiller peak capacity requirements by 40-50%', 'Zero maintenance structural concrete thermal storage that lasts 100+ years'],
    cons: ['Requires precast structural concrete engineering and crane placement during construction', 'Requires exposed architectural concrete ceiling aesthetic'],
    maintenanceNotes: 'Standard ventilation fan maintenance.',
    materialsNeeded: ['Precast hollow-core concrete floor slabs', 'Airtight slab core crossover manifolds', 'Low-energy ventilation distribution fan'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Patented in Sweden (TermoDeck) and utilized in landmark zero-energy institutional and residential buildings worldwide.',
    tags: ['Hollow Core', 'TermoDeck', 'Thermal Activation', 'Concrete Mass', 'Zero Ductwork']
  },
  {
    id: 96,
    name: 'Solid-State Thermoelectric Peltier Cooling Ceiling Panels',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Very Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Artificial / Mechanical',
    houseZone: 'Mechanical & Active',
    climateSuitability: ['All Climates', 'Temperate', 'Hot-Arid'],
    coolingMechanism: 'Phase Change',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '3°C – 6°C silent radiant ceiling cooling',
    tempDropCelsiusRange: [2.5, 5.5],
    estimatedCostRangeUSD: '$4,000 – $15,000',
    summary: 'Ceiling panels embedded with solid-state semiconductor Peltier junction chips that chill the room side while transferring heat to a heat-pipe or hydronic loop on the attic side.',
    architecturalPrinciple: 'Thermoelectric Peltier effect: Passing a DC electrical current through bi-metal semiconductor junctions causes heat to be absorbed on one face (creating a chilled ceiling) and rejected on the opposite face with zero refrigerants or compressors.',
    constructionNotes: 'Requires DC power transformers and efficient heat rejection heat-pipe sink connected to attic ventilation or geothermal ground loop.',
    pros: ['100% solid-state cooling with zero moving parts, zero noise, and zero chemical refrigerants', 'Instantaneous temperature adjustment and precise digital microprocessor control', 'Ultra-slim profile panel can be integrated flush into luxury modern ceilings'],
    cons: ['Lower coefficient of performance (COP) than conventional vapor-compression systems at high temperature differentials', 'High semiconductor manufacturing cost per square meter'],
    maintenanceNotes: 'Inspect DC power supply voltage calibration.',
    materialsNeeded: ['Thermoelectric semiconductor ceiling cassettes', 'High-efficiency DC power supply', 'Heat-pipe heat rejection radiator'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Modern solid-state physics engineering developed for aerospace, submarine, and futuristic residential cooling.',
    tags: ['Thermoelectric', 'Peltier Cooling', 'Solid State', 'Zero Refrigerant', 'Silent']
  },
  {
    id: 97,
    name: 'Biomimetic Termite Mound Architecture (Eastgate Principles)',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Very Expensive',
    effortLevel: 'High',
    difficulty: 'Extremely Difficult',
    nature: 'Natural',
    houseZone: 'Orientation & Layout',
    climateSuitability: ['Hot-Arid', 'Tropical', 'All Climates'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '6°C – 12°C passive temperature regulation without central AC',
    tempDropCelsiusRange: [5, 11],
    estimatedCostRangeUSD: '$8,000 – $30,000+ (Architectural engineering)',
    summary: 'Designing the building with porous internal convective labyrinths, vertical central chimneys, and lower intake tunnels inspired by African Macrotermes termite mounds.',
    architecturalPrinciple: 'Self-regulating stack-buoyancy respiration: Passive convective air channels exploit diurnal ambient temperature swings and metabolic/solar heat to drive self-sustaining air loops that maintain a constant 24°C interior.',
    constructionNotes: 'Requires advanced computational fluid dynamics (CFD) airflow modeling, high-mass concrete/masonry internal baffles, and tuned vertical exhaust chimneys.',
    pros: ['Uses 90% less energy than conventional air-conditioned buildings of comparable size', 'Continuous, fresh, self-regulating natural airflow without mechanical compressor systems', 'Iconic, pioneering bioclimatic architectural form'],
    cons: ['Requires sophisticated architectural and fluid dynamics engineering from day one', 'Virtually impossible to retrofit onto standard stick-built timber homes'],
    maintenanceNotes: 'Inspect internal duct dampers and intake screens.',
    materialsNeeded: ['High thermal mass structural core', 'CFD-optimized convective vertical shafts', 'Automated airflow damper valves'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Pioneered by architect Mick Pearce in the Eastgate Centre (Harare, Zimbabwe) and CH2 Building (Melbourne).',
    tags: ['Biomimicry', 'Termite Mound', 'Eastgate Principle', 'Self Regulating', 'Zero Energy']
  },
  {
    id: 98,
    name: 'Double-Skin Facade with Integrated Dynamic Sun-Cavity (DSF)',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Very Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Hybrid',
    houseZone: 'Walls & Envelope',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Temperate'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '5°C – 9°C thermal transmission reduction / 60% acoustic cut',
    tempDropCelsiusRange: [4.5, 8.5],
    estimatedCostRangeUSD: '$6,000 – $22,000',
    summary: 'A pair of glass facades separated by a 200–900 mm wide ventilated air cavity containing motorized shading louvers, exhausting solar heat out the top.',
    architecturalPrinciple: 'Thermodynamic buffer zone: In summer, bottom and top cavity vents are opened. Solar heat absorbed by the internal motorized blinds creates a rapid chimney updraft that exhausts 80%+ of heat out the roof.',
    constructionNotes: 'Outer skin is typically single or laminated glass; inner skin is high-performance insulated double glass. Include operable maintenance access doors to clean inside the cavity.',
    pros: ['Enables large panoramic glass walls without severe solar greenhouse overheating', 'Cuts exterior street noise by up to 35–45 dB', 'Allows natural window ventilation even during high-rise windstorms and rain'],
    cons: ['Substantial architectural engineering and double glazing hardware cost', 'Consumes 200–500 mm of perimeter floor footprint'],
    maintenanceNotes: 'Clean interior cavity glass panes once every 1–2 years.',
    materialsNeeded: ['Structural steel/aluminum curtain wall mullions', 'Laminated outer glass & double-glazed inner wall', 'Motorized cavity blinds & operable vent dampers'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Pioneered in European sustainable architecture (Foster + Partners, RPBW) and high-end residential estates.',
    tags: ['Double Skin Facade', 'DSF', 'Dynamic Cavity', 'Glass House', 'Thermal Buffer']
  },
  {
    id: 99,
    name: 'Aerosol-Based Whole-House Envelope Micro-Sealing (AeroBarrier)',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Moderate',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Walls & Envelope',
    climateSuitability: ['All Climates', 'Extreme Climates', 'Hot-Humid', 'Hot-Arid'],
    coolingMechanism: 'Thermal Mass / Lag',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: 'Reduces outdoor hot air infiltration by 70-85% / 2°C – 4°C indoor drop',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$1,500 – $3,500 (Full house process in 4 hours)',
    summary: 'Pressurizing the house with a blower door while spraying microscopic non-toxic acrylic aerosol sealant particles that automatically find and seal all hidden envelope air cracks.',
    architecturalPrinciple: 'Eliminates unconditioned air infiltration: Standard homes leak massive volumes of blistering 40°C outdoor air through tiny gaps behind baseboards, electrical boxes, and top plates. Sealing leaks down to < 0.6 ACH50 stops heat influx permanently.',
    constructionNotes: 'Cover finished vertical windows and doors. Set up blower door to pressurize the building. Run automated aerosol injector nozzles until real-time computer readout hits desired airtightness target (e.g. 0.6 ACH50).',
    pros: ['Achieves Passivhaus-level extreme airtightness in just 3 to 4 hours', 'Real-time computerized feedback guarantees exact airtightness verification', 'Stops hot humid air leaks, dust infiltration, pest bugs, and outdoor smoke permanently'],
    cons: ['Must be performed by a certified technician with specialized equipment', 'Building MUST have mechanical balanced fresh air ventilation (like an ERV) installed once sealed'],
    maintenanceNotes: 'Sealant does not degrade (rated for 50+ years).',
    materialsNeeded: ['AeroBarrier aerosolized non-toxic acrylic sealant', 'Calibrated blower door and compressor system'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Invented at UC Davis Western Cooling Efficiency Center and standard for high-performance home building.',
    tags: ['AeroBarrier', 'Airtightness', 'Envelope Sealing', 'Passivhaus', 'Stop Air Leaks']
  },
  {
    id: 100,
    name: 'Wind-Powered Rotary Roof Turbine Ventilators (Whirlybirds)',
    category: 'Advanced & Experimental Designs',
    categorySlug: 'advanced-experimental-designs',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '8°C – 15°C attic temperature reduction / 2°C – 3.5°C indoor drop',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$60 – $180 per unit',
    summary: 'Spherical aluminum aerodynamic finned turbine vents mounted near the roof ridge that spin in the slightest breeze, mechanically extracting hot air from the attic.',
    architecturalPrinciple: 'Centrifugal vacuum suction: Wind blowing across the curved aerodynamic turbine fins causes the spherical head to spin, creating a continuous centrifugal suction vortex that pulls superheated attic air upward and throws it out.',
    constructionNotes: 'Cut 300 mm hole in roof decking near the ridge. Mount flashing base plate, level the turbine neck using the built-in adjustable pitch collar, and fasten with roofing screws and sealant.',
    pros: ['Operates 100% free with zero electrical wiring or utility bill impact', 'Spins with even a tiny 5 mph breeze, providing active mechanical exhaust', 'Very inexpensive, durable rust-free aluminum, and easy weekend DIY installation'],
    cons: ['Can develop minor squeaking bearing noise after 10+ years if cheap unsealed bearings are used (choose dual permanently lubricated teflon bearings)', 'Inactive on completely dead-calm windless days (relies on thermal buoyancy)'],
    maintenanceNotes: 'Inspect rotation and lubricate or replace turbine head every 8–12 years.',
    materialsNeeded: ['12" or 14" rust-free aluminum rotary turbine roof vent with dual sealed bearings', 'Roofing sealant / butyl tape', 'Galvanized roofing nails/screws'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Invented in the 1930s (Edmonds / Lomanco) and a classic cooling staple on roofs across Australia, the USA, and Asia.',
    tags: ['Whirlybird', 'Roof Turbine', 'Wind Powered', 'Attic Exhaust', 'Zero Electricity', 'DIY']
  }
];
