/**
 * HITR - 100 House Cooling Architectural Designs
 * Part 1: Designs 1 to 35
 * Covers: Passive Design & Orientation (1-10), Roof & Attic (11-20), Windows & Glazing (21-35)
 */

import { CoolingDesign } from '../types';

export const DESIGNS_PART_1: CoolingDesign[] = [
  // -------------------------------------------------------------
  // CATEGORY 1: PASSIVE DESIGN & ORIENTATION (1 - 10)
  // -------------------------------------------------------------
  {
    id: 1,
    name: 'North-South Solar Orientation',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Orientation & Layout',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '3°C – 6°C surface / 2°C – 4°C indoor',
    tempDropCelsiusRange: [2, 5],
    estimatedCostRangeUSD: '$0 – $500 (Design phase)',
    summary: 'Orienting the long axis of the house East-West so major window openings face North and South, minimizing harsh low-angle East/West solar gains.',
    architecturalPrinciple: 'Low solar elevation angles in the East (morning) and West (late afternoon) deliver severe horizontal thermal flux that is difficult to shade. South facing facades receive high-angle summer sun that is trivially blocked with simple horizontal overhangs, while North facades receive diffuse skylight.',
    constructionNotes: 'Implemented during site planning and foundation layout. Ensure habitable day zones are positioned along the North (or shaded South) facade.',
    pros: ['Zero operational or material cost when planned upfront', 'Reduces peak summer air-conditioning loads by 25-40%', 'Enables optimal passive winter heating balance in temperate zones'],
    cons: ['Virtually impossible to retrofit on existing foundations', 'Constrained by municipal lot geometry and road frontage regulations'],
    maintenanceNotes: 'Zero maintenance required throughout the lifecycle of the building.',
    materialsNeeded: ['Sun path solar chart / Heliodon analysis', 'Standard foundation framing'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Documented by Vitruvius in Roman architecture and traditional Greek Olynthus courtyard layouts.',
    tags: ['Orientation', 'Passive Solar', 'Zero Cost', 'Design Phase']
  },
  {
    id: 2,
    name: 'Compact Building Form (Low Surface-to-Volume Ratio)',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Orientation & Layout',
    climateSuitability: ['Hot-Arid', 'Hot-Humid', 'All Climates'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '2°C – 4°C indoor heat retention reduction',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$0 (Lowers structural material costs)',
    summary: 'Minimizing the building envelope surface area relative to its interior volume (e.g. cubic or rectangular geometry) to reduce conductive and radiant heat influx.',
    architecturalPrinciple: 'Heat transfer rate Q = U * A * ΔT. By reducing envelope area (A) per unit of usable floor space, conductive heat gain through walls and roofs drops proportionally.',
    constructionNotes: 'Avoid complex floor plans with excessive perimeter corners, cantilevers, or sprawling wings in extreme heat zones.',
    pros: ['Reduces total building material and framing costs', 'Lower thermal envelope leakage', 'Simplifies HVAC ducting runs and passive airflow paths'],
    cons: ['May limit customized architectural exterior articulation', 'Requires careful interior layout to ensure natural light reaches the center core'],
    maintenanceNotes: 'No maintenance required.',
    materialsNeeded: ['Efficient floor plan geometry', 'Standard building envelope materials'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Observed in traditional Pueblo adobe clusters and North African medina dwellings.',
    tags: ['Geometry', 'Surface Area', 'S/V Ratio', 'Efficiency']
  },
  {
    id: 3,
    name: 'Deep Roof Overhangs & Eaves',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Moderate',
    effortLevel: 'Medium',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Mediterranean'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '3°C – 5°C on wall surfaces, 2°C – 3.5°C interior',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$800 – $2,500',
    summary: 'Extending roof rafters 60–120 cm beyond the exterior wall line to cast complete summer shadow over windows and upper walls while admitting low winter sun.',
    architecturalPrinciple: 'Calculated using solar zenith angles. High noon summer sun (65°–80° altitude) is geometrically intercepted, preventing direct solar radiation from striking vertical glazing.',
    constructionNotes: 'Size overhangs according to latitude. Overhang depth = (Window Height) / (tan(Summer Solstice Altitude) - tan(Winter Solstice Altitude)). Structural outriggers or brackets required for spans > 90 cm.',
    pros: ['Blocks 80-90% of direct solar gain on glazing', 'Protects wall finishes from driving rain and UV degradation', 'Simple timber/steel framing extension'],
    cons: ['Must be engineered for regional wind uplift and hurricane suction', 'Can slightly reduce natural indoor ambient daylighting on overcast days'],
    maintenanceNotes: 'Inspect underside soffits and fascia paint every 3–5 years.',
    materialsNeeded: ['Extended roof rafters / trusses', 'Soffit panels with integrated ventilation', 'Structural hurricane ties / brackets'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Key feature of Japanese Minka houses, Swiss chalets, and American Craftsman / Prairie architecture.',
    tags: ['Roof Eaves', 'Solar Geometry', 'Shading', 'Glazing Protection']
  },
  {
    id: 4,
    name: 'Interior Thermal Mass (Concrete, Brick, Stone)',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Moderate',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Walls & Envelope',
    climateSuitability: ['Hot-Arid', 'Mediterranean', 'Temperate'],
    coolingMechanism: 'Thermal Mass / Lag',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '4°C – 7°C peak daytime temperature dampening',
    tempDropCelsiusRange: [3, 6],
    estimatedCostRangeUSD: '$2,000 – $7,000',
    summary: 'Dense interior concrete floors (polished slab), exposed masonry walls, or water walls that absorb internal daytime sensible heat and release it during cool nights.',
    architecturalPrinciple: 'Thermal inertia and thermal phase shift (thermal lag of 6–10 hours). Volumetric heat capacity (Cv) of dense materials buffers diurnal indoor temperature swings, moderating peaks.',
    constructionNotes: 'Thermal mass MUST be insulated on the exterior and exposed directly to the interior air without carpet or drop ceilings. Pair with night-purge ventilation.',
    pros: ['Dampens severe diurnal temperature spikes', 'Zero mechanical energy consumption', 'Provides durable, elegant structural flooring and finishes'],
    cons: ['Ineffective in tropical climates where night temperatures remain above 25°C', 'High dead-weight load requires robust foundation footing'],
    maintenanceNotes: 'Occasional surface sealing for polished concrete or exposed stone.',
    materialsNeeded: ['Polished concrete slab (100–150 mm thick)', 'Dense clay brick or basalt stone', 'Exterior sub-slab rigid insulation (XPS/EPS)'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Fundamental in Mediterranean stone villas, Iranian mudbrick domes, and Anasazi cliff dwellings.',
    tags: ['Thermal Inertia', 'Thermal Lag', 'Concrete Slab', 'Diurnal Swing']
  },
  {
    id: 5,
    name: 'Night Purge Ventilation (Nocturnal Cooling)',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Free',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Ventilation & Airflow',
    climateSuitability: ['Hot-Arid', 'Mediterranean', 'Temperate'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '3°C – 6°C indoor morning temperature drop',
    tempDropCelsiusRange: [3, 6],
    estimatedCostRangeUSD: '$0 – $150 (Manual or basic timer)',
    summary: 'Flushing cool nighttime air through open windows and vents while closing the building tightly at dawn to trap the chilled thermal mass throughout the day.',
    architecturalPrinciple: 'Replaces warm indoor air with ambient night air when outdoor ambient temp drops 8°C+ below daytime peaks, discharging stored heat from interior structural masonry and furniture.',
    constructionNotes: 'Ensure insect screens and secure tilt-and-turn windows or security louvers are installed for safe overnight ventilation.',
    pros: ['100% free operating cost', 'Significantly refreshes indoor air quality and oxygen levels', 'Works synergistically with interior thermal mass'],
    cons: ['Requires daily homeowner discipline or automated motorized actuators', 'Ineffective during humid heatwaves without a nocturnal temperature dip'],
    maintenanceNotes: 'Clean window insect screens twice per season.',
    materialsNeeded: ['Secure lockable window stays / security grilles', 'High-flow insect screens', 'Optional smart automated window actuators'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Standard operating lifestyle across the Mediterranean, Middle East, and Southwest USA for centuries.',
    tags: ['Night Flush', 'Free Cooling', 'Nocturnal', 'Zero Energy']
  },
  {
    id: 6,
    name: 'Natural Cross-Ventilation',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Orientation & Layout',
    climateSuitability: ['All Climates', 'Hot-Humid', 'Tropical', 'Temperate'],
    coolingMechanism: 'Sensory / Convective Chill',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '2°C – 3.5°C sensible / 3°C – 5°C perceived wind chill',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$0 (Planning) / $400 – $1,200 (Retrofit window)',
    summary: 'Placing operable window openings on opposing or adjacent walls aligned with prevailing summer breeze paths to induce continuous airflow across living spaces.',
    architecturalPrinciple: 'Wind pressure differential (Bernoulli principle): positive pressure on the windward facade pushes air into the room, while negative suction on the leeward facade extracts it rapidly.',
    constructionNotes: 'Make inlet openings slightly smaller than outlet openings to create a venturi nozzle velocity acceleration across occupant zones.',
    pros: ['Dramatically enhances physiological evaporative skin cooling (0.5–1.0 m/s airspeed feels 3°C cooler)', 'Zero electrical consumption', 'Eliminates stagnant air zones and indoor humidity buildup'],
    cons: ['Dependent on outdoor wind availability and direction', 'May draw in outdoor dust, pollen, or traffic noise'],
    maintenanceNotes: 'Inspect window seals and lubricate hinges annually.',
    materialsNeeded: ['Operable casement or louvre windows', 'Strategic interior door louver grilles'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Central principle of Caribbean timber cottages, Malay stilt houses, and Hawaiian plantation bungalows.',
    tags: ['Cross Breeze', 'Wind Pressure', 'Airflow', 'Skin Cooling']
  },
  {
    id: 7,
    name: 'Stack Effect (Vertical Buoyancy Venting)',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Moderate',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Natural',
    houseZone: 'Orientation & Layout',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '3°C – 5°C interior warm air stratification relief',
    tempDropCelsiusRange: [2, 5],
    estimatedCostRangeUSD: '$600 – $2,200',
    summary: 'Utilizing tall double-height spaces, stairwells, or roof lanterns with high exhaust vents to allow rising hot air to escape, drawing cooler air in from ground-level shaded openings.',
    architecturalPrinciple: 'Thermal buoyancy: Warm air has lower density than cool air (Δρ = ρ0 * β * ΔT), creating upward buoyant draft and pressure gradients across height differential (ΔH).',
    constructionNotes: 'Max vertical height between low air inlet and high air outlet maximizes stack pressure (P = C * h * (Ti - To)). Equip upper vents with motorized remote switches.',
    pros: ['Works even on completely windless, sweltering days', 'Continuously purges hot stratified ceiling heat', 'Creates open, airy architectural spatial volumes'],
    cons: ['Needs height difference (minimum 3–4 meters to function effectively)', 'Upper vents must seal tightly in winter to prevent unwanted heat escape'],
    maintenanceNotes: 'Test and clean motorized operable high vent louvers twice a year.',
    materialsNeeded: ['High-level operable clerestory or roof lantern vents', 'Low-level shaded intake dampers / windows'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Central feature of Roman atriums, Victorian central lightwells, and Ottoman lantern towers.',
    tags: ['Stack Effect', 'Thermal Buoyancy', 'Vertical Venting', 'Convection']
  },
  {
    id: 8,
    name: 'Passive Solar Thermal Chimney',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Moderate',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['Hot-Arid', 'Mediterranean', 'Tropical'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '3°C – 6°C continuous induced draft cooling',
    tempDropCelsiusRange: [3, 5],
    estimatedCostRangeUSD: '$1,500 – $4,500',
    summary: 'A vertical glazed shaft painted black on the interior that superheats under sunlight, creating powerful thermal updrafts that pull cool air from ground or underground earth tubes.',
    architecturalPrinciple: 'Intense solar radiation superheats air inside the narrow black chimney channel (reaching 55°C+), dramatically accelerating buoyancy exhaust and creating continuous suction inside the house.',
    constructionNotes: 'Face the glazed collector South or West. Use a black-painted metal absorber plate behind tempered low-iron glass with backdraft damper at top.',
    pros: ['Generates strong ventilation airflow precisely during the hottest sunlit hours', 'No moving mechanical parts or electrical motors required', 'Can be integrated with underground earth cooling tubes'],
    cons: ['Requires specialized structural roof flashing and weatherproofing', 'Must be properly baffled to avoid reverse airflow during rain or winter'],
    maintenanceNotes: 'Clean exterior glass panel and check top backdraft flap seasonally.',
    materialsNeeded: ['Tempered low-iron solar glazing', 'Black matte absorber sheet', 'Insulated chimney shaft', 'Backdraft shutter damper'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Engineered during 19th-century passive solar research and refined in contemporary bioclimatic desert architecture.',
    tags: ['Solar Chimney', 'Induced Draft', 'Solar Thermal', 'Ventilation']
  },
  {
    id: 9,
    name: 'Open Bioclimatic Floor Plan',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Orientation & Layout',
    climateSuitability: ['Hot-Humid', 'Tropical', 'Temperate'],
    coolingMechanism: 'Sensory / Convective Chill',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '1.5°C – 3°C air stagnant zone elimination',
    tempDropCelsiusRange: [1, 3],
    estimatedCostRangeUSD: '$0 (Design) / $800 – $3,000 (Wall removal)',
    summary: 'Designing internal spaces with minimal full-height dividing partition walls, using slatted screens and wide doorways to allow unhindered interior air circulation.',
    architecturalPrinciple: 'Internal partitions create aerodynamic drag and resistance (high friction coefficient), suffocating natural breezes. Open plans maintain uninterrupted laminar airflow paths.',
    constructionNotes: 'When privacy is required, use operable Japanese-style shoji screens, acoustic louvers, or high transom vents above doors instead of solid floor-to-ceiling drywall.',
    pros: ['Eliminates hot stagnant air pockets in corners and corridors', 'Increases perceived spaciousness and daylight penetration', 'Allows single air-moving fan to service multiple functional zones'],
    cons: ['Reduced acoustic privacy between rooms', 'Requires structural beams (glulam or steel) to support long ceiling spans without loadbearing walls'],
    maintenanceNotes: 'No special maintenance required.',
    materialsNeeded: ['Louvered internal doors', 'Structural header beams', 'Acoustic baffle panels'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Traditional Southeast Asian longhouses and Japanese machiya sliding screen architecture.',
    tags: ['Open Plan', 'Unobstructed Breeze', 'Fluid Dynamics', 'Spatial Flow']
  },
  {
    id: 10,
    name: 'Elevated Structure on Stilts / Piloti',
    category: 'Passive Design & Orientation',
    categorySlug: 'passive-design-orientation',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Subterranean & Foundation',
    climateSuitability: ['Hot-Humid', 'Tropical', 'Coastal'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '3°C – 5°C envelope cooling + elimination of ground radiant heat',
    tempDropCelsiusRange: [3, 5],
    estimatedCostRangeUSD: '$6,000 – $22,000',
    summary: 'Raising the ground floor 1.2 to 3 meters above the terrain on concrete columns or timber piers, allowing cool ground-level winds to sweep underneath the floor slab.',
    architecturalPrinciple: 'Air speed increases with elevation away from ground boundary layer friction. Elevating the floor enables 360° sub-floor convective cooling and isolates the living zone from hot re-radiating soil.',
    constructionNotes: 'Use reinforced concrete columns or rot-resistant timber (treated glulam, ironwood). Insulate or vent floor joists according to seasonal humidity.',
    pros: ['Immense cooling airflow beneath living spaces', 'Protects against tropical flash floods and damp soil humidity', 'Creates shaded ground-level workshop / outdoor living pavilion below'],
    cons: ['Higher structural engineering and foundation pier costs', 'Requires accessibility staircases or ramps'],
    maintenanceNotes: 'Inspect structural column footings and termite shields annually.',
    materialsNeeded: ['Reinforced concrete piloti / footings', 'Engineered floor joists', 'Subfloor breathable vapor barrier'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Centuries-old standard in Southeast Asian Malay architecture, Amazonian palafitos, and Le Corbusier modernism.',
    tags: ['Stilts', 'Piloti', 'Subfloor Airflow', 'Flood Resilience']
  },

  // -------------------------------------------------------------
  // CATEGORY 2: ROOF & ATTIC SOLUTIONS (11 - 20)
  // -------------------------------------------------------------
  {
    id: 11,
    name: 'Cool Roof (High-Albedo White Elastomeric Coating)',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Roof & Attic',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Mediterranean'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '25°C – 35°C roof surface drop / 3°C – 6°C attic/interior drop',
    tempDropCelsiusRange: [3, 6],
    estimatedCostRangeUSD: '$250 – $900 (DIY) / $1,200 – $2,500 (Pro)',
    summary: 'Applying a specialized bright white elastomeric or acrylic roof coating with Solar Reflectance Index (SRI) > 100 that reflects over 85% of solar radiation.',
    architecturalPrinciple: 'High solar reflectance (albedo >= 0.80) bounces visible and UV rays, while high thermal emittance (>= 0.90) rapidly radiates away absorbed heat back into the sky.',
    constructionNotes: 'Power wash the roof substrate thoroughly. Apply 2 coats of elastomeric cool roof coating using a heavy nap roller or commercial airless sprayer.',
    pros: ['Immediate 20-30°C reduction in exterior roof temperature', 'Extends roofing membrane lifespan by shielding from UV degradation', 'Incredible cost-to-benefit ratio and extremely easy DIY application'],
    cons: ['Can cause glare for taller neighboring structures', 'Requires periodic pressure washing to maintain high albedo over time'],
    maintenanceNotes: 'Rinse off accumulated dust and dirt every 1–2 years; recoat every 7–10 years.',
    materialsNeeded: ['High-solids elastomeric acrylic roof coating (SRI > 100)', 'Roof primer', 'Heavy duty roller & extension pole'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Traditional whitewashed lime coatings throughout the Greek Cyclades, Andalusia, and North Africa.',
    tags: ['Cool Roof', 'High Albedo', 'Reflective Paint', 'Low Cost', 'DIY']
  },
  {
    id: 12,
    name: 'Extensive Vegetative Green Roof (Sedum Blanket)',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['Mediterranean', 'Temperate', 'Hot-Humid', 'All Climates'],
    coolingMechanism: 'Evaporative Cooling',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '30°C – 40°C roof surface drop / 4°C – 8°C ceiling temperature drop',
    tempDropCelsiusRange: [4, 7],
    estimatedCostRangeUSD: '$4,000 – $15,000',
    summary: 'A living layer of drought-tolerant sedum succulent plants, drainage fleece, and lightweight substrate engineered over a heavy-duty waterproof roof membrane.',
    architecturalPrinciple: 'Evapotranspiration of living vegetation continuously cools the roof surface, while the multi-layer soil substrate provides massive thermal insulation (R-value) and thermal mass.',
    constructionNotes: 'Verify structural load capacity (extensive green roofs add 60–150 kg/m² wet weight). Must include root-barrier membrane, drainage cup matting, and overflow scuppers.',
    pros: ['Lowers roof surface temperature to below ambient air temperature', 'Absorbs 70–90% of storm water runoff, preventing urban flooding', 'Creates stunning aesthetic beauty and urban biodiversity habitat'],
    cons: ['Significant structural dead weight requires reinforced roof framing', 'Higher initial investment cost and leak repair complexity'],
    maintenanceNotes: 'Weed occasionally in spring; inspect drainage outlets after major storms.',
    materialsNeeded: ['EPDM/TPO Root barrier membrane', 'Dimpled drainage and water retention sheet', 'Lightweight engineered green roof soil (75–120 mm)', 'Pre-grown sedum vegetation mats'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Traditional Nordic sod roofs and contemporary European ecological architecture.',
    tags: ['Green Roof', 'Living Roof', 'Sedum', 'Evapotranspiration', 'Insulation']
  },
  {
    id: 13,
    name: 'Evaporative Blue Roof (Stormwater Thermal Buffer)',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Hybrid',
    houseZone: 'Roof & Attic',
    climateSuitability: ['Hot-Arid', 'Mediterranean', 'Temperate'],
    coolingMechanism: 'Evaporative Cooling',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '5°C – 8°C top floor ceiling temp reduction',
    tempDropCelsiusRange: [4, 8],
    estimatedCostRangeUSD: '$5,000 – $18,000',
    summary: 'An engineered flat roof retention system that temporarily ponds controlled depths of rainwater (50–100 mm) to absorb solar energy and dissipate heat through water evaporation.',
    architecturalPrinciple: 'Water has a high specific heat capacity (4,184 J/kg·K) and huge latent heat of vaporization (2,260 kJ/kg). Sun energy is consumed evaporating water instead of heating the building.',
    constructionNotes: 'Requires industrial grade double-layer waterproofing, specialized slow-drain restrictor valves, and structural calculation for water dead load (100 kg/m² per 100mm depth).',
    pros: ['Dramatically stabilizes top floor ceiling temperatures', 'Decelerates stormwater discharge into municipal sewer systems', 'Can be integrated with solar evaporative misting systems'],
    cons: ['High structural load calculation and zero tolerance for membrane punctures', 'Requires mosquito control/larvicide management in stagnant ponding situations'],
    maintenanceNotes: 'Inspect drain flow restrictors and waterproofing seals biannually.',
    materialsNeeded: ['Commercial ballast waterproofing membrane', 'Controlled orifice drainage restrictors', 'Thermal ballasts and algae inhibitors'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Developed in industrial thermal engineering and modern sponge-city resilience designs.',
    tags: ['Blue Roof', 'Water Storage', 'Latent Heat', 'Stormwater']
  },
  {
    id: 14,
    name: 'Attic Radiant Barrier (Reflective Aluminum Foil)',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Roof & Attic',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Mediterranean'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '10°C – 18°C attic temperature reduction / 2°C – 4°C room drop',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$120 – $400 (DIY roll materials)',
    summary: 'Stapling a layer of highly reflective perforated aluminum foil to the underside of roof rafters in the attic, facing an open air space.',
    architecturalPrinciple: 'Up to 93% of summer heat transfer across an attic is radiant electromagnetic infrared waves. Aluminum foil has low emissivity (e < 0.05), blocking 95%+ of radiant heat transfer to the attic floor.',
    constructionNotes: 'Must face an open air gap of at least 25 mm to function. Staple to underside of roof trusses or rafters. Use perforated foil to allow water vapor transpiration and avoid moisture buildup.',
    pros: ['Very inexpensive and easy DIY installation with a staple gun', 'Reduces HVAC duct heat gain by 40-50% in unconditioned attics', 'Lasts decades with no operating cost'],
    cons: ['Dust accumulation over years can decrease reflectivity if laid flat on attic floor (staple to rafters instead)', 'Requires careful attic ventilation so moisture can escape'],
    maintenanceNotes: 'Check every few years that staples remain secure and foil is dust-free.',
    materialsNeeded: ['Perforated double-sided radiant barrier foil roll (e.g. 500-1000 sq ft)', 'Heavy duty staple gun & staples', 'Utility knife'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Developed by NASA for spacecraft thermal blankets and adapted to residential building codes in the 1980s.',
    tags: ['Radiant Barrier', 'Attic Foil', 'Infrared Reflection', 'Cheap', 'DIY']
  },
  {
    id: 15,
    name: 'Solar-Powered Attic Extraction Fan',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Moderate',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Hybrid',
    houseZone: 'Roof & Attic',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '10°C – 15°C attic air drop / 2°C – 3.5°C ceiling temp drop',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$250 – $600',
    summary: 'A roof-mounted exhaust fan driven by an integrated photovoltaic panel that automatically spins fastest during peak sun, exhausting superheated attic air.',
    architecturalPrinciple: 'Trapped attic air can reach 65°C+ on sunny days. Active solar-powered volumetric air evacuation (500–1,500 CFM) continuously forces replacement with cooler outdoor air via soffit vents.',
    constructionNotes: 'Requires adequate intake soffit vent area (1 sq ft of intake per 300 sq ft of attic floor). Cut hole in roof decking, apply silicone roofing sealant, and screw down flashing securely.',
    pros: ['Zero electric bill impact (100% solar powered)', 'Runs automatically at highest speed when the sun is hottest', 'Reduces conductive heat transfer through top floor ceilings'],
    cons: ['If soffit intake area is inadequate, it may create negative pressure and pull conditioned air from inside living areas', 'Motor brushes/bearings require eventual replacement after 8-12 years'],
    maintenanceNotes: 'Wipe photovoltaic panel dust clean once a year.',
    materialsNeeded: ['Solar attic fan unit (25W-40W PV panel)', 'Roofing sealant / butyl tape', 'Galvanized roofing screws'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Modern evolution of passive turbine roof vents and electric gable fans.',
    tags: ['Solar Fan', 'Attic Exhaust', 'Solar Powered', 'Active Ventilation']
  },
  {
    id: 16,
    name: 'Continuous Vented Ridge Cap',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '5°C – 10°C attic temperature reduction',
    tempDropCelsiusRange: [2, 3.5],
    estimatedCostRangeUSD: '$150 – $450 (During roofing/retrofit)',
    summary: 'A continuous horizontal vent installed along the entire roof peak apex beneath ridge cap shingles, providing unbroken convective air exhaust.',
    architecturalPrinciple: 'Exploits natural stack buoyancy and negative wind suction pressure along the roof peak to uniformly evacuate rising hot attic air without hot-spot dead zones.',
    constructionNotes: 'Cut a 25–40 mm slot in the roof decking along the ridge peak on both sides of the ridge board. Fasten the corrugated mesh ridge vent roll and cap with matching shingles.',
    pros: ['Extremely discreet visual profile with no unsightly protruding dome vents', 'Provides continuous, uniform exhaust across the full roof length', 'Zero mechanical moving parts to wear out'],
    cons: ['Must be balanced with equal or greater low-level soffit intake vents', 'Snow accumulation in winter can temporarily block airflow'],
    maintenanceNotes: 'Inspect end plugs to ensure weather seal remains intact.',
    materialsNeeded: ['Shingle-over continuous ridge vent roll / plastic sections', 'Long roofing nails', 'Ridge cap shingles'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Standardized modern roofing best practice adopted internationally since the 1990s.',
    tags: ['Ridge Vent', 'Roof Peak', 'Continuous Exhaust', 'Stack Effect']
  },
  {
    id: 17,
    name: 'Perforated Continuous Soffit Vents',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '4°C – 8°C attic temperature reduction',
    tempDropCelsiusRange: [1.5, 3],
    estimatedCostRangeUSD: '$100 – $350',
    summary: 'Perforated aluminum or vinyl panels installed along the underside of roof overhang eaves that introduce cool outdoor ambient air into the attic base.',
    architecturalPrinciple: 'Creates the critical low-pressure air intake zone necessary to feed the convective thermal chimney loop towards high-level ridge vents (1:300 ventilation rule).',
    constructionNotes: 'Install insulation baffles (rafter vents) between roof rafters to prevent blown-in fiberglass or cellulose attic insulation from blocking soffit airflow paths.',
    pros: ['Keeps cool air washing continuously along the underside of the hot roof deck', 'Prevents attic moisture accumulation and winter ice damming', 'Low cost and clean finished appearance'],
    cons: ['Can become clogged with windblown dust, cobwebs, or overgrown insulation if baffles are omitted', 'Requires correct sizing to match ridge exhaust area'],
    maintenanceNotes: 'Blow out dust with leaf blower or vacuum every 2–3 years.',
    materialsNeeded: ['Perforated vinyl/aluminum soffit panels', 'Cardboard/foam rafter insulation baffles', 'Fastening trim screws'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Evolved from slotted timber eaves in early 20th-century vernacular housing.',
    tags: ['Soffit Vents', 'Attic Intake', 'Airflow Loop', 'Baffles']
  },
  {
    id: 18,
    name: 'Double Roof (Safari / Fly Roof)',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Moderate',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['Hot-Humid', 'Tropical', 'Hot-Arid'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '5°C – 10°C interior ceiling temperature drop',
    tempDropCelsiusRange: [4, 7],
    estimatedCostRangeUSD: '$1,800 – $5,500',
    summary: 'A secondary, lightweight outer roof mounted 20–40 cm above the primary insulated roof, absorbing solar radiation and allowing cross-breezes to wash the gap.',
    architecturalPrinciple: 'Decouples solar radiative thermal load completely from the waterproof building envelope. The outer fly roof gets hot while open convective winds dissipate the heat before it can conduct into the house.',
    constructionNotes: 'Build outer shade structure using corrugated metal, bamboo, or timber battens on standoff brackets. Keep the intermediate cavity wide open on all four sides for maximum airflow.',
    pros: ['Virtually eliminates direct solar heat load on the ceiling', 'Dramatically reduces tropical rain noise on living rooms', 'Extends the life of the primary waterproof roof membrane by 3x'],
    cons: ['Increases overall building height and wind uplift profile', 'Requires additional structural framing supports'],
    maintenanceNotes: 'Inspect standoff mounting brackets for corrosion and bolt tightness.',
    materialsNeeded: ['Lightweight corrugated metal or polycarbonate roofing', 'Galvanized steel standoff posts/purlins', 'Engineered wind-bracing'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Widely used in African safari camps, tropical research stations, and Australian Outback homesteads.',
    tags: ['Double Roof', 'Safari Roof', 'Fly Roof', 'Decoupled Envelope']
  },
  {
    id: 19,
    name: 'Natural Thatch & Reed Roofing',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Cheap',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['Tropical', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Thermal Mass / Lag',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '4°C – 7°C ceiling temperature drop',
    tempDropCelsiusRange: [3, 6],
    estimatedCostRangeUSD: '$1,200 – $4,500 (Region-dependent)',
    summary: 'A 200–300 mm thick roof crafted from layered dried water reeds, palm fronds, or wheat straw, offering natural microscopic air-pocket insulation.',
    architecturalPrinciple: 'Traps millions of stagnant micro air cells within dry plant fibers, providing extremely high thermal insulation (R-value ~ R-30+) and allowing warm indoor humidity to naturally transpire out.',
    constructionNotes: 'Requires steep roof pitch (minimum 45° to 50°) to shed torrential tropical rain quickly. Layer reeds densely and tie with tarred cord or stainless steel wire to roof battens.',
    pros: ['100% natural, biodegradable, and renewable local materials', 'Outstanding acoustic sound dampening and thermal insulation', 'Zero embodied carbon footprint'],
    cons: ['Elevated fire risk unless treated with non-toxic fire retardant sprays', 'Susceptible to nesting birds, insects, and requires re-thatching ridge every 8-15 years'],
    maintenanceNotes: 'Annual inspection for moss, wire tensioning, and chemical fire-retardant touchup.',
    materialsNeeded: ['Water reed / thatch bundles', 'Hazel spars / stainless wire', 'Timber roof battens'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Traditional across English countryside cottages, Polynesian fales, and African rondavels.',
    tags: ['Thatch', 'Natural Fiber', 'High Insulation', 'Vernacular']
  },
  {
    id: 20,
    name: 'Ventilated Terracotta Roof Tiles (Air-Gap Battens)',
    category: 'Roof & Attic Solutions',
    categorySlug: 'roof-attic-solutions',
    costLevel: 'Moderate',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Natural',
    houseZone: 'Roof & Attic',
    climateSuitability: ['Mediterranean', 'Hot-Arid', 'Temperate'],
    coolingMechanism: 'Thermal Mass / Lag',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '3°C – 6°C attic/interior temperature drop',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$2,500 – $7,000',
    summary: 'Curved S-tile or barrel terracotta clay tiles mounted on counter-battens, creating continuous undulating ventilation channels beneath the tiles.',
    architecturalPrinciple: 'Earthen clay provides thermal mass and slow heat release, while the semicircular barrel tile shape forms open convective chimneys from eave to ridge, flushing heated air out before reaching roof decking.',
    constructionNotes: 'Install vertical counter-battens over a breathable waterproof underlayment, followed by horizontal tile battens to guarantee unblocked vertical drainage and air channels.',
    pros: ['Lifespan of 50 to 100+ years with outstanding fire and rot resistance', 'Self-ventilating under-tile convective current', 'Timeless Mediterranean aesthetic appeal'],
    cons: ['Heavy weight (40–55 kg/m²) requires sturdy roof framing', 'Brittle under heavy impact (e.g. large hail or walking directly on tiles)'],
    maintenanceNotes: 'Replace cracked individual tiles if damaged.',
    materialsNeeded: ['Terracotta barrel / S-tiles', 'Treated timber counter-battens (38x50mm)', 'Breathable high-temp roof underlayment'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Standard across Spanish mission architecture, Italian villas, and Southern French mas.',
    tags: ['Terracotta', 'Clay Tiles', 'Counter-Battens', 'Air Gap']
  },

  // -------------------------------------------------------------
  // CATEGORY 3: WINDOW & GLAZING TREATMENTS (21 - 35)
  // -------------------------------------------------------------
  {
    id: 21,
    name: 'Spectrally Selective Low-E Glass Coating',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Moderate',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '3°C – 5°C room temperature drop / 60-70% solar gain reduction',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$350 – $900 per window unit',
    summary: 'Microscopically thin metallic oxide coatings applied to glass that transmit visible light while reflecting unwanted near-infrared heat rays.',
    architecturalPrinciple: 'Achieves a low Solar Heat Gain Coefficient (SHGC < 0.25) with a high Light-to-Solar-Gain (LSG) ratio > 1.7, blocking invisible solar thermal radiation while keeping indoor rooms bright.',
    constructionNotes: 'Specified on surface #2 (inside face of exterior pane) in hot cooling-dominated climates to repel heat before it enters the insulating gas cavity.',
    pros: ['Blocks up to 75% of solar infrared heat gain without making windows dark', 'Protects interior hardwood floors and furniture from UV fading', 'Permanent microscopic coating inside the sealed insulated glass unit (IGU)'],
    cons: ['Higher upfront purchase cost than clear builder-grade glass', 'Cannot be applied as a DIY spray on existing glass (requires factory IGU replacement)'],
    maintenanceNotes: 'Clean with standard non-abrasive glass cleaner.',
    materialsNeeded: ['Double-pane Low-E insulated glass units (IGU)'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Pioneered in modern materials science labs in the 1980s and now the benchmark global energy standard.',
    tags: ['Low-E Glass', 'Spectrally Selective', 'SHGC', 'Infrared Rejection']
  },
  {
    id: 22,
    name: 'Argon & Krypton Gas-Filled Double Windows',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Moderate',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Temperate', 'Hot-Arid'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '2°C – 4°C room temp stabilization',
    tempDropCelsiusRange: [1.5, 3.5],
    estimatedCostRangeUSD: '$400 – $1,100 per window',
    summary: 'Injecting inert argon or krypton gas between double or triple glass panes to drastically reduce conductive and convective heat transmission.',
    architecturalPrinciple: 'Argon gas has 34% lower thermal conductivity (k = 0.016 W/m·K) and higher molecular weight than atmospheric air, suppressing internal convective thermal loops inside the glazing cavity.',
    constructionNotes: 'Installed as complete hermetically sealed IGU window cassettes with warm-edge composite spacer bars to avoid thermal bridging along the perimeter frame.',
    pros: ['Significantly improves overall window U-factor (U < 1.4 W/m²K)', 'Excellent acoustic sound isolation from exterior street traffic', 'Eliminates interior winter condensation and summer perimeter hot-zones'],
    cons: ['Gas can slowly transpire at ~0.5-1% per year if seals are compromised', 'Slightly higher cost than standard air-filled double glazing'],
    maintenanceNotes: 'Inspect perimeter silicone caulk bead every 5 years.',
    materialsNeeded: ['Argon gas insulated window cassettes', 'Low-expansion window perimeter foam'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Commercialized in high-performance German Passivhaus engineering.',
    tags: ['Argon Gas', 'Thermal Insulation', 'U-Factor', 'Energy Star']
  },
  {
    id: 23,
    name: 'Triple Glazing with Warm-Edge Spacers',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Expensive',
    effortLevel: 'Medium',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['Extreme Climates', 'Hot-Arid', 'Temperate'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '3°C – 6°C radiant window zone drop',
    tempDropCelsiusRange: [2.5, 5.5],
    estimatedCostRangeUSD: '$700 – $1,800 per window',
    summary: 'Three panes of glass bounding two independent gas-filled cavities with dual Low-E coatings, creating the ultimate thermal barrier against exterior heat waves.',
    architecturalPrinciple: 'Double cavity thermal damping drives whole-window U-factors down to U < 0.8 W/m²K (R-7 equivalent), practically equal to an insulated wall section.',
    constructionNotes: 'Heavy weight (30 kg/m² of glass) requires reinforced window rough openings and heavy-duty hinges/mechanisms.',
    pros: ['Near-zero radiant heat transmission through the glass', 'Superior exterior acoustic noise blockage', 'Extreme thermal comfort directly beside large picture windows'],
    cons: ['Higher cost and heavy frame profile', 'Overkill for mild temperate climates'],
    maintenanceNotes: 'Standard window cleaning.',
    materialsNeeded: ['Triple-pane IGU assemblies', 'Reinforced structural window bucks'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Originated in Scandinavian and Passivhaus architectural standards.',
    tags: ['Triple Glazing', 'Passivhaus', 'Max Insulation', 'Acoustics']
  },
  {
    id: 24,
    name: 'Operable External Wooden / Aluminum Shutters',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Moderate',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Mediterranean', 'Hot-Arid', 'Tropical'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '4°C – 7°C indoor temperature drop on exposed rooms',
    tempDropCelsiusRange: [3, 6],
    estimatedCostRangeUSD: '$150 – $500 per window pair',
    summary: 'Exterior-mounted hinged or sliding louvered shutters that stop solar radiation on the outside of the glass before greenhouse heat trapping occurs.',
    architecturalPrinciple: 'Stopping solar photons on the exterior facade converts radiation to exterior surface heat that dissipates into outdoor wind, preventing indoor greenhouse trapping (indoor blinds trap heat inside).',
    constructionNotes: 'Mount with corrosion-resistant stainless steel pintle hinges directly to exterior window trim or masonry wall. Provide tie-backs to hold shutters open in breezy weather.',
    pros: ['Stops up to 90% of solar radiation before hitting glass', 'Adds storm protection, security, and timeless architectural character', 'Adjustable louvers allow breeze while blocking direct sun glare'],
    cons: ['Requires manual opening/closing twice daily or motorized automation', 'Exterior wood requires periodic painting or staining'],
    maintenanceNotes: 'Repaint or oil timber every 3–4 years; lubricate hinges annually.',
    materialsNeeded: ['Exterior louvered shutters (cedar, composite, or aluminum)', 'Heavy duty exterior strap hinges & pintles', 'Holdback shutter dogs'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Signature element of French, Italian, Spanish, and Colonial Caribbean architecture.',
    tags: ['External Shutters', 'Solar Block', 'Exterior Shading', 'Traditional']
  },
  {
    id: 25,
    name: 'Louvered Jalousie Windows',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Moderate',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['Hot-Humid', 'Tropical', 'Coastal'],
    coolingMechanism: 'Sensory / Convective Chill',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '2°C – 4°C convective indoor temperature relief',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$200 – $600 per unit',
    summary: 'Parallel glass or timber slats set in a crank-operated track that tilt open simultaneously to provide 100% window opening area for unrestricted ventilation even in rain.',
    architecturalPrinciple: 'Standard sliding or hung windows only open 50% of the wall opening area. Jalousies open 95-100% of the aperture, maximizing airflow velocity and continuous evaporative skin cooling.',
    constructionNotes: 'Angle slats downward (30°–45°) during tropical downpours to maintain ventilation without water ingress. Use frosted or tinted glass slats for privacy and shading.',
    pros: ['100% ventilation opening capacity', 'Ventilates continuously during tropical downpours without rain blowing inside', 'Allows precise adjustment of incoming airflow direction'],
    cons: ['Poor airtightness (leaks conditioned air if running winter heating or central AC)', 'Lower security resistance against forced entry unless heavy-gauge bars are fitted'],
    maintenanceNotes: 'Clean and oil the crank worm-gear operator once a year.',
    materialsNeeded: ['Jalousie louver window frame track kits', 'Tempered safety glass slats (100–150 mm width)'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Ubiquitous in mid-century Hawaii, Florida, Caribbean, and Australian Queenslander architecture.',
    tags: ['Jalousie', 'Louvered Window', '100% Airflow', 'Rain Venting']
  },
  {
    id: 26,
    name: 'Smart Electrochromic Glass (Dynamic Tinting)',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Very Expensive',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '4°C – 8°C room peak cooling load reduction',
    tempDropCelsiusRange: [3.5, 7],
    estimatedCostRangeUSD: '$800 – $2,200 per sq meter of glass',
    summary: 'Electronically tintable glass that changes tint level automatically via low-voltage electrical impulses in response to sunlight intensity or smart home sensors.',
    architecturalPrinciple: 'Reversible electrochemical lithium-ion intercalation in tungsten oxide nanolayers alters solar transmittance dynamically (SHGC drops from 0.45 clear to 0.09 tinted) while maintaining views.',
    constructionNotes: 'Requires low-voltage DC wiring to each window frame rough opening, central control driver box, and integration with exterior solar irradiance sensors.',
    pros: ['Preserves exterior views without blinds, curtains, or mechanical louvers', 'Reduces peak cooling loads by up to 20% dynamically', 'Automates tinting based on real-time sun angles and occupancy'],
    cons: ['Very high initial hardware and installation expense', 'Takes 3 to 10 minutes to complete full tint transition'],
    maintenanceNotes: 'Firmware updates for controller and electrical connection inspections.',
    materialsNeeded: ['Electrochromic IGU glass panels', 'Low-voltage DC power supply & wiring harnesses', 'Smart irradiance sensor controller'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'High-tech architectural glazing developed for modern commercial towers and luxury bioclimatic homes.',
    tags: ['Electrochromic', 'Smart Glass', 'Dynamic Tinting', 'High-Tech']
  },
  {
    id: 27,
    name: 'DIY Reflective Solar Window Film',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Mediterranean'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '3°C – 5°C room drop / 75% solar heat rejection',
    tempDropCelsiusRange: [2, 4.5],
    estimatedCostRangeUSD: '$30 – $100 per room (DIY kit)',
    summary: 'Applying a static-cling or adhesive metallized PET film directly to the interior or exterior surface of existing window glass to bounce solar infrared heat.',
    architecturalPrinciple: 'Micro-thin vacuum-sputtered aluminum or ceramic particles in the polyester matrix reflect up to 78% of incoming solar heat and 99% of damaging UV rays.',
    constructionNotes: 'Clean glass thoroughly with soapy water and razor scraper. Spray slip solution, roll out film, and squeegee out all bubbles from the center outward.',
    pros: ['Extremely inexpensive and fast DIY installation in 1-2 hours', 'Cuts glaring sun reflection on computer/TV screens instantly', 'Can be removed without residue if using non-adhesive static cling films'],
    cons: ['Slightly darkens visible light entering the room', 'If applied incorrectly on some dual-pane windows in extreme climates, can cause thermal stress crack risk (use exterior-rated film)'],
    maintenanceNotes: 'Wipe with soft microfiber cloth; avoid ammonia-based cleaners.',
    materialsNeeded: ['Solar control window film roll', 'Application solution (water + baby shampoo)', 'Precision squeegee and snap-blade razor'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Widely popular retrofit solution in modern automotive and residential energy upgrades.',
    tags: ['Window Film', 'Solar Foil', 'Cheap', 'DIY', 'Glare Reduction']
  },
  {
    id: 28,
    name: 'Retractable Canvas / Acrylic Awnings',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Temperate', 'Mediterranean', 'Hot-Arid'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '3°C – 6°C indoor temp drop / 65-77% solar gain cut',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$180 – $750 per window',
    summary: 'Overhead fabric canopies mounted above south- and west-facing windows that extend to cast cooling shade in summer and retract to welcome winter solar warmth.',
    architecturalPrinciple: 'Reduces solar heat gain by 65% on south windows and up to 77% on west windows by intercepting direct solar rays before they reach window glass.',
    constructionNotes: 'Mount heavy-duty brackets directly into structural wall framing studs using lag bolts. Adjust pitch angle to 45° for optimal summer noon shading.',
    pros: ['Reduces room heat buildup immediately upon deployment', 'Retractable flexibility allows maximum solar heating during cold winter months', 'Enhances outdoor patio usability and curb appeal'],
    cons: ['Must be retracted during extreme windstorms to avoid fabric tearing', 'Fabric canopy requires replacement every 8–12 years due to UV exposure'],
    maintenanceNotes: 'Hose down fabric seasonally; lubricate crank gear mechanism.',
    materialsNeeded: ['Solution-dyed acrylic awning fabric unit (e.g. Sunbrella)', 'Heavy-duty wall mounting brackets and lag screws'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Staple of Mediterranean seaside towns and American Main Street storefronts since the 19th century.',
    tags: ['Awnings', 'Retractable Canvas', 'Seasonal Flexibility', 'Exterior Shade']
  },
  {
    id: 29,
    name: 'Interior & Exterior Architectural Light Shelves',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Moderate',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Natural',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Temperate'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Medium (Moderate Retrofit)',
    tempDropEstimate: '2°C – 4°C localized radiant cooling + daylighting',
    tempDropCelsiusRange: [1.5, 3.5],
    estimatedCostRangeUSD: '$250 – $800 per window',
    summary: 'A horizontal shelf mounted at upper window height that reflects natural daylight deep onto the ceiling while shading the lower vision glass below.',
    architecturalPrinciple: 'Splits window into vision glass (shaded below) and daylighting clerestory (above). High-albedo upper shelf surface bounces light 5–8 meters deep into rooms without direct solar heat gain.',
    constructionNotes: 'Paint upper shelf surface semi-gloss white or use anodized aluminum. Position shelf at approximately 2.1 meters above finished floor height.',
    pros: ['Eliminates need for artificial daytime electric lights (reducing internal heat load)', 'Cuts direct solar glare and radiant heat on occupants sitting near windows', 'Adds sophisticated architectural interior/exterior depth'],
    cons: ['Requires tall ceilings (2.7m+) to function effectively', 'Interior shelf top collects dust and requires occasional wiping'],
    maintenanceNotes: 'Dust upper reflective surface once every few months.',
    materialsNeeded: ['High-reflectance composite or aluminum shelf board', 'Structural cantilever wall brackets'],
    diyFeasibility: 'Intermediate DIY / Handyman',
    historicalVernacularContext: 'Refined in early daylighting engineering and contemporary sustainable school/office designs.',
    tags: ['Light Shelf', 'Daylighting', 'Glare Control', 'Indirect Light']
  },
  {
    id: 30,
    name: 'High Clerestory Windows with Venting Actuators',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Moderate',
    effortLevel: 'High',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid', 'Temperate'],
    coolingMechanism: 'Convective Venting',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '3°C – 5°C ceiling thermal layer purge',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$800 – $2,500 per unit',
    summary: 'Narrow horizontal bands of windows positioned just below the ceiling line that open via chain-actuators to flush out superheated stratified air.',
    architecturalPrinciple: 'Leverages the vertical thermal stack effect at the highest ceiling boundary layer while introducing soft, glare-free indirect daylight from the sky vault.',
    constructionNotes: 'Face clerestory North for cool, constant daylight or South with calculated roof overhangs. Install motorized 24V linear chain actuators wired to a wall switch.',
    pros: ['Effortlessly purges the hottest air in the room without creating lower draft turbulence', 'Provides privacy while filling rooms with panoramic sky daylight', 'Can be left open overnight for continuous secure ventilation'],
    cons: ['Difficult to access manually without motorized chain actuators', 'Requires complex high-wall framing and header beams'],
    maintenanceNotes: 'Test motorized chain actuators and check perimeter seals annually.',
    materialsNeeded: ['Awning/hopper clerestory window units', 'Electric chain window actuator motors', 'Remote wall control switch'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Key feature of ancient Egyptian hypostyle halls, Gothic cathedrals, and Frank Lloyd Wright Usonian homes.',
    tags: ['Clerestory', 'High Venting', 'Stack Purge', 'Natural Light']
  },
  {
    id: 31,
    name: 'Deeply Recessed Windows (Deep Revealing / Splayed Jambs)',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Moderate',
    effortLevel: 'Medium',
    difficulty: 'Difficult',
    nature: 'Natural',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['Hot-Arid', 'Mediterranean', 'Tropical'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '3°C – 5°C solar heat gain reduction',
    tempDropCelsiusRange: [2, 4],
    estimatedCostRangeUSD: '$400 – $1,200 (Framing phase)',
    summary: 'Setting window frames 200–350 mm deep into the exterior wall envelope, creating built-in self-shading masonry or plaster reveals.',
    architecturalPrinciple: 'The thick exterior wall envelope acts as a permanent geometric sunshade, blocking acute angle morning, afternoon, and midday solar rays before they touch the glass.',
    constructionNotes: 'Splay interior window jambs at 45° angles to maximize daylight distribution into the room while keeping exterior window reveals crisp and deep.',
    pros: ['Permanent, zero-maintenance architectural self-shading with no mechanical parts to fail', 'Splayed interior jambs soften visual contrast and reduce eye glare', 'Provides deep cozy window sills for plants or seating'],
    cons: ['Requires thick exterior wall construction (masonry, ICF, straw bale, or double stud)', 'Difficult to retrofit on thin 2x4 standard timber stud walls'],
    maintenanceNotes: 'Zero maintenance.',
    materialsNeeded: ['Thick wall framing / masonry bucks', 'Waterproof sill flashing pans'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Hallmark of Portuguese and Spanish thick-walled adobe/stone haciendas.',
    tags: ['Recessed Window', 'Self Shading', 'Deep Reveal', 'Vernacular']
  },
  {
    id: 32,
    name: 'Internal Cellular Honeycomb Blinds',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Temperate', 'Hot-Arid'],
    coolingMechanism: 'Thermal Mass / Lag',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '2°C – 3.5°C localized room temperature drop',
    tempDropCelsiusRange: [1.5, 3],
    estimatedCostRangeUSD: '$50 – $180 per window',
    summary: 'Window blinds designed with hexagonal internal air pockets (single or double cell) with a white reflective exterior backing that traps hot air at the glass.',
    architecturalPrinciple: 'Trapped dead-air cellular pockets provide an insulation barrier (R-value ~ R-3.5 to R-4.5) while the white outer foil fabric reflects incoming solar rays back out through the window.',
    constructionNotes: 'Order custom sizes for tight inside-mount installation (with side tracks if available) to prevent convective air loops around blind edges.',
    pros: ['Very affordable and clean modern aesthetic', 'Dual season benefit: insulates against winter cold and summer heat', 'Easy 15-minute DIY installation with simple top brackets'],
    cons: ['Heat trapped between blind and glass is still technically inside the building envelope (less efficient than exterior shutters)', 'Accumulates dust inside cells if neglected'],
    maintenanceNotes: 'Vacuum gently with brush attachment every few months.',
    materialsNeeded: ['Double-cell insulating honeycomb blinds', 'Mounting clips & screws'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Invented in the late 1970s energy crisis to upgrade single-pane window insulation.',
    tags: ['Honeycomb Blinds', 'Cellular Shades', 'Dead Air Insulator', 'DIY']
  },
  {
    id: 33,
    name: 'Ceramic Fritted Glass (Silk-Screened Pattern Matrix)',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Expensive',
    effortLevel: 'Medium',
    difficulty: 'Moderate',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Hot-Arid', 'Hot-Humid'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'Low (Best for New Construction)',
    tempDropEstimate: '3°C – 6°C solar heat reduction',
    tempDropCelsiusRange: [2.5, 5],
    estimatedCostRangeUSD: '$450 – $1,200 per window unit',
    summary: 'Glass with permanent ceramic micro-dots or geometric line patterns fused onto surface #2, reflecting solar radiation and reducing glare.',
    architecturalPrinciple: 'Ceramic mineral frit dots reflect and absorb 40–70% of direct solar heat flux while maintaining transparent outward visibility between the dot matrix.',
    constructionNotes: 'Specified in factory glass fabrication. Custom patterns (gradients, dots, lines) can be tuned to deliver denser shading at the top of the pane where sun angles are steepest.',
    pros: ['Permanent ceramic fusion that never degrades, peels, or fades under UV', 'Significant bird-friendly collision deterrence feature', 'Cuts severe solar glare in modern glass walls'],
    cons: ['Higher manufacturing lead time and cost', 'Pattern cannot be turned off or removed once glass is tempered'],
    maintenanceNotes: 'Standard glass cleaning.',
    materialsNeeded: ['Custom ceramic fritted insulated glass panels'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Developed in high-performance institutional and modern museum architecture.',
    tags: ['Fritted Glass', 'Ceramic Matrix', 'Bird Safe', 'Solar Control']
  },
  {
    id: 34,
    name: 'Vacuum Insulated Glazing (VIG)',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Very Expensive',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Artificial / Mechanical',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['Extreme Climates', 'Hot-Arid', 'Temperate'],
    coolingMechanism: 'Radiation Shielding',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '4°C – 7°C radiant boundary drop',
    tempDropCelsiusRange: [3, 6],
    estimatedCostRangeUSD: '$900 – $2,500 per window',
    summary: 'Ultra-thin (8.3 mm) double glazing featuring a microscopic 0.2 mm vacuum gap separated by micro-pillars, eliminating conductive and convective heat transfer.',
    architecturalPrinciple: 'A high vacuum eliminates all gas molecules (pressure < 0.001 Pa), preventing conductive and convective thermal transfer entirely and matching the thermal insulation of solid brick walls (U < 0.60 W/m²K).',
    constructionNotes: 'Because VIG is as thin as single glazing (8–10 mm), it can be retrofitted directly into historic wooden window frames without altering exterior architectural heritage profiles.',
    pros: ['Highest thermal insulation value of any glazing in existence (R-12 to R-14+)', 'Ultra-slim profile fits into historic vintage window sashes', 'Outstanding sound insulation and edge-to-edge clarity'],
    cons: ['Premium cutting-edge price tag', 'Microscopic separation pillar grid is faintly visible under close inspection'],
    maintenanceNotes: 'Standard glass care.',
    materialsNeeded: ['Vacuum Insulated Glass (VIG) units', 'High-grade glazing putty/silicone'],
    diyFeasibility: 'Licensed Contractor Required',
    historicalVernacularContext: 'Pioneered by the University of Sydney and manufactured by leading Japanese and European glass firms.',
    tags: ['Vacuum Glass', 'VIG', 'Historic Retrofit', 'Max Thermal Insulation']
  },
  {
    id: 35,
    name: 'Living Window Boxes with Broad-Leaf Plants',
    category: 'Window & Glazing Treatments',
    categorySlug: 'window-glazing-treatments',
    costLevel: 'Cheap',
    effortLevel: 'Low',
    difficulty: 'Easy',
    nature: 'Natural',
    houseZone: 'Windows & Glazing',
    climateSuitability: ['All Climates', 'Mediterranean', 'Tropical', 'Temperate'],
    coolingMechanism: 'Evaporative Cooling',
    retrofitSuitability: 'High (DIY / Easy Retrofit)',
    tempDropEstimate: '2°C – 4°C microclimate temperature drop at window sill',
    tempDropCelsiusRange: [1.5, 3.5],
    estimatedCostRangeUSD: '$40 – $150 per window',
    summary: 'Exterior window-mounted planter boxes filled with lush, broad-leaf foliage, herbs, or cascading vines that cool incoming window breezes via evapotranspiration.',
    architecturalPrinciple: 'Plant leaves consume solar energy to transpire water vapor into the air, creating a localized humid adiabatic microclimate that pre-cools air before it passes through the window opening.',
    constructionNotes: 'Mount sturdy brackets into exterior wall studs. Use lightweight potting soil with perlite and select hardy plants (e.g. hostas, geraniums, ivy, or mint). Include drip trays to prevent water staining on siding.',
    pros: ['Extremely charming visual beauty, aroma, and curb appeal', 'Provides living micro-shade and evaporative cooling right at the air intake', 'Grow fresh culinary herbs right at your kitchen window'],
    cons: ['Requires regular watering (or simple automated micro-drip line)', 'Window box must be securely bolted to withstand soil and water weight'],
    maintenanceNotes: 'Water regularly during dry summer spells and trim overgrown foliage.',
    materialsNeeded: ['Exterior window planter box & heavy-duty brackets', 'Potting mix & mulch', 'Broad-leaf regional plants'],
    diyFeasibility: 'DIY Friendly',
    historicalVernacularContext: 'Classic feature of Bavarian, Swiss alpine, and Mediterranean stone village windows.',
    tags: ['Window Box', 'Living Shade', 'Evapotranspiration', 'Microclimate', 'DIY']
  }
];
