import type { HeatReading, LandInfo, PatternAnalysis, Plan } from "../api";

export function formatBlockBrief(input: {
  location: string;
  picked: { lat: number; lng: number } | null;
  reading: HeatReading | null;
  land: LandInfo | null;
  pattern: PatternAnalysis | null;
  plan: Plan | null;
  afterNote?: string | null;
}): string {
  const lines: string[] = [
    `# HITR block brief — ${input.location}`,
    "",
  ];
  if (input.picked) {
    lines.push(`Spot: ${input.picked.lat.toFixed(5)}, ${input.picked.lng.toFixed(5)}`);
  }
  if (input.reading) {
    lines.push(`Now: ${input.reading.temp_f}°F (${input.reading.temp_c}°C) · ${input.reading.risk} · source ${input.reading.source}`);
  }
  if (input.land) lines.push(`Land: ${input.land.label}`);
  if (input.pattern) lines.push(`Pattern: ${input.pattern.pattern_label} — ${input.pattern.summary}`);
  if (input.afterNote) lines.push(`Scenario: ${input.afterNote}`);
  if (input.plan) {
    lines.push("");
    lines.push(`## Plan — ${input.plan.change_label} (level ${input.plan.change_level})`);
    lines.push(`Scale: ${input.plan.scale.label} — touches ${input.plan.scale.touches}`);
    lines.push(`Cost buckets: ${input.plan.interventions.map((i) => i.cost).join(", ") || "none"}`);
    const top = input.plan.interventions.slice(0, 3);
    if (top.length) {
      lines.push("Top actions:");
      top.forEach((i) => lines.push(`${i.rank}. ${i.what} — ${i.impact} (${i.cost})`));
    } else {
      lines.push(input.plan.note ?? "No interventions.");
    }
  } else {
    lines.push("");
    lines.push("No plan generated yet.");
  }
  lines.push("");
  lines.push("Generated by HITR. Cooling °C claims follow uhiFactors caps, not LLM invention.");
  return lines.join("\n");
}
